### ISSUE TITLE
Don't auto-open compose box when narrowing to a stream/topic pair

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#104]
Users are most likely to want to read messages (and only sometimes will want to compose a reply; and even if they do they probably want to read the messages first), and opening the compose box hides most of the message feed, so I think it'd probably be better to not auto-open the compose box.

**Comment by kunall17** [comment]
@timabbott can be closed if #118 servers the purpose?

**Comment by timabbott** [comment]
yeah this was resolved by #118 I think.
