### ISSUE TITLE
Close stream sidebar when narrowing to a new stream

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#105]
When you narrow to a stream in the Android app, it leaves the stream sidebar open.  While this is nice for if they want to now re-narrow to a topic within the stream, I imagine it'd be far more common that they want to see the actual messages in the stream (and one can always pull out the sidebar again to renarrow to a topic).

**Comment by kunall17** [comment]
Well if we press the name of the stream it will close the drawer as well, but if the user clicks the stream in the right it expands and the drawer remains open! 
Would you like to change the behavior to close the drawer?

**Comment by kunall17** [comment]
@timabbott what about this one?

**Comment by timabbott** [comment]
I see, the current behavior is that you decide whether to press the name or the whitespace to the right, and that determines whether it closes the drawer.  That makes sense (though would perhaps be nice to teach somehow).  I'm content with the current functionality here, so closing.
