### ISSUE TITLE
Custom zulip server defaults to http

### ISSUE THREAD

**Issue by rwbarton** [zulip/zulip-android#109]
I see there was a PR specifically changing this (#78), but from an end-user perspective I don't understand the change. Won't real Zulip servers run over https? It wasn't obvious to me that I had to add https:// to my Zulip server name.

**Comment by timabbott** [comment]
Yes, this should default to HTTP.  I bet the HTTP change was to make it work nicely with a development environment running on localhost, but we should never use HTTP in production.

**Comment by kunall17** [comment]
OkHttp supports redirect from http to https, I'll implement code to save the server url after it redirects when we fetch the `"v1/get_auth_backends"` in #101 branch.

**Comment by timabbott** [comment]
From a security perspective, we should try HTTPS only by default.  Otherwise, the app might be vulnerable to man-in-the-middle attacks.

**Comment by kunall17** [comment]
So should we not allow them to use https or show a message that if you don't use https there can be security issues?

**Comment by timabbott** [comment]
I think we should require HTTPS, with a special exception for the development environment (can we e.g. check this by IP address or something else that's not doing a fetch over HTTP)?

**Comment by kunall17** [comment]
We can check for development server by a new api route, for fetching `settings.PRODUCTION` in the server?

Maybe we can do like this, if they specifically mentioned http in the server url then we use http showing user a message that its not recommended over http and if not specified then we connect over https?

**Comment by rwbarton** [comment]
That sounds good to me.

**Comment by lfaraone** [comment]
> We can check for development server by a new api route, for fetching settings.PRODUCTION in the server?

So if you incorrectly specify "http://zulipchat.org", an active MITM can force a downgrade.

I'd prefer that using HTTP either require a very onerous opt-in or require running a development build of the app.

**Comment by timabbott** [comment]
Yeah, I was going to say the same thing.  Let's just default to HTTPS, and if they hand-specify HTTP, show a warning with text like "HTTP is insecure, and we recommend using it only for testing the Zulip Android app against a development environment.  Are you sure you want to use HTTP?".  As a proposal, the button options would be:

"Switch to HTTPS / Use HTTP / Cancel"

("Switch to HTTPS" would just modify their URL to be HTTPS instead.)

but one could skip the "use HTTPS" one.

How does that proposal sound?

**Comment by timabbott** [comment]
It'd be good to get this resolved quickly, since it is a security-relevant issue (and I hope should be fairly quick?).

**Comment by niftynei** [comment]
This has been merged and will be fixed in the next release.
