### ISSUE TITLE
Messages are out of order

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#131]
I've noticed that since the new look and feel update, messages are often times getting inserted in the wrong order. For example when narrowed to a private chat, 10 or so older messages are appearing at the bottom of the list, below newer messages.  The timestamps on these messages are correct, but how they're ordered is not.

**Comment by timabbott** [comment]
I imagine it should be fairly easy to ensure ordering is correct -- messages should always appear sorted by message ID.

**Comment by timabbott** [comment]
I think this message ordering issue is kinda a blocker for releasing RecyclerView to production...
