### ISSUE TITLE
Register Zulip app as a way to share files

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#133]
When you're in your gallery type app and click share, it shows you a ton of apps that you can use to share files with.  We should add file upload support to the Zulip Android app and register it as a share files provider.

**Comment by Sam1301** [comment]
I'd like to work on this

**Comment by brainwane** [comment]
Hi @Sam1301! Go ahead. (And, in the future, it's fine for you to say "I'm going to work on this issue" -- you don't need to ask for permission.)
