### ISSUE TITLE
No way to close compose box (and can obscure last message in feed)

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#134]
Even though the compose box isn't always open, once you open it, there's no way to close it, and it obscures the bottom message in the few.  We might want to add an "x" to close.

**Comment by kunall17** [comment]
The UI would get very much filled up if we add that, already there are many buttons! 
We can just swipe up to hide the chatBox!

**Comment by timabbott** [comment]
Yeah, that's a nice idea.  Might need to advertise it in an onboarding flow eventually to make it discoverable, but sounds good!

**Comment by timabbott** [comment]
Oh, I see, you can close it by scrolling up/down.  hmm.  Yeah, probably adding removal via swipe away is good enough,

**Comment by kunall17** [comment]
@timabbott should we implement a swipe right/left to close the chatBox?
I think the current swipe up to close that is fine!
