### ISSUE TITLE
On Narrow, Keep Narrowed Conversation in View

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#145]
Branching from a suggestion on #139.

When narrowing, we should ensure the narrowing is done in a way where the message that you touched to initiate the narrow on stays in view (rather than jolting around). See for notes on how this works in the webapp.

http://zulip.readthedocs.io/en/latest/pointer.html

**Comment by timabbott** [comment]
Yeah this would be super cool.  I'd recommend implementing it in the way the webapp says it would like to be implemented, not the way it currently works.  That may involve some Zulip backend changes -- I'm happy to help make those :)

**Comment by Sam1301** [comment]
I'd like to work on this issue :)
