### ISSUE TITLE
Pushing the Back Button after Narrowing should return to previous conversation location

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#146]
When narrowing via clicking on a user's name (PR #100 ), pushing the back button doesn't take me back to the message that I clicked from, but resets it all the way back to the default ZulipActivity view. I'd expect to return to the place that I clicked into the user messages from.

**Comment by kenodoggy** [comment]
in progress

**Comment by kenodoggy** [comment]
[PR #100](https://github.com/zulip/zulip-android/pull/100) is not yet merged

**Comment by niftynei** [comment]
Could not reproduce.
