### ISSUE TITLE
Uploaded images not displayed properly by the Android app

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#148]
I've gotten a few reports that the Android app doesn't display images which were uploaded via the file uploads feature.  I suspect the problem is that the way uploaded image files work in Zulip on web is that the URL in the message is a special URL on the Zulip server that serves a redirect to a temporary URL containing the image.  The intent is the browser then loads that image and caches it.

I suspect the Android app is not handling that time-limited redirect in quite the right way.

**Comment by koziodigitalinc** [comment]
Working on this.

**Comment by niftynei** [comment]
hey @koziodigitalinc I tried this out but wasn't able to see the image that i pasted up.  

Here's the expected (from web client):
![image](https://cloud.githubusercontent.com/assets/1097769/18690483/4e842ac6-7f5c-11e6-8729-1acd3bb5040b.png)


Here's the actual (from mobile client):
![screenshot_20160920-175847](https://cloud.githubusercontent.com/assets/1097769/18690516/658bada2-7f5c-11e6-8afb-95d5ff7ff174.png)

**Comment by timabbott** [comment]
From server logs, I think the problem is that the user_uploads URLs incorrectly have the `api/` in the path.

**Comment by Sam1301** [comment]
Hi, I'd like to work on this issue.

**Comment by patrykpoborca** [comment]
@Sam1301 This is an issue related to: https://github.com/zulip/zulip-android/pull/149

It's completed yet not merged

**Comment by brainwane** [comment]
Hi, @Sam1301 - do you need any help finding another issue to work on? Maybe you could join us in https://zulip.tabbott.net/ to chat about it!
