### ISSUE TITLE
Integration bots profile image make the app crash

### ISSUE THREAD

**Issue by ff-** [zulip/zulip-android#15]
When there's a bot in the stream, the app tries to fetch its profile image from Gravatar, while its url is a relative path for the server.

**Comment by lfaraone** [comment]
Can you include the stack trace and the URI its trying to fetch?

**Comment by ff-** [comment]
@lfaraone in the meanwhile I just fixed this, should I directly open a pull request?

**Comment by lfaraone** [comment]
sure, thanks! go ahead.​

**Comment by ryansnowboarder** [comment]
I'm trying to fix some things on the Android app and I'm hitting a wall while logging in. How do I do that (requires a @zulip.com login)?

**Comment by niftynei** [comment]
fixed in #211
