### ISSUE TITLE
Implement a way to notify when a new message is recieved

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#153]
This is very important for the app, as currently no notifications is given to the user if a new message is recieved when the user scrolls to bottom then only he knows if a new message is recieved.

Suggestion: When in homeList (not narrowed to a topic or stream currently) then we can change the title to Zulip (2) which shows 2 new messages received, and the stream drawer will show which stream/topic received the message by #120.

Complexity: One problem will be while implementing this would be, when we send a message through chatBox by [AsyncSend ](https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncSend.java) java file, after sending this message, the server resend's this message to the android App to save in the database. 

But yeah we can also easily distinguish by checking who is the sender of this message and based on that we can increase the count.

**Comment by reached-ankita** [comment]
Hey! I would like to work on this issue.

**Comment by brainwane** [comment]
@reached-ankita Go ahead, and -- [after you give it a try](https://blogs.akamai.com/2013/10/you-must-try-and-then-you-must-ask.html) -- please let us know if you need some guidance.

**Comment by reached-ankita** [comment]
Sure! :)

**Comment by kunall17** [comment]
@reached-ankita are you working on this?

**Comment by reached-ankita** [comment]
Yes I am! I had exams this week in college so couldn't do it by now. But I am working on this!
