### ISSUE TITLE
Usability Improvements

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#166]
Here's a bunch of small usability improvements the app could use:

[ ] When I scroll to the end of a stream of messages, there's no buffer between the last message and the bottom. If the response textbox is open, it'll cover up the last portion of the screen.
[ ] When a large message is received, the screen bounces around, making it hard to scroll past. It seems like it's re-loading from the server or something.
[ ] The behavior of how the 'reply to' box gets filled is unpredictable.  I accidentally sent a message to the wrong person this morning because it re-filled with a different conversation.

**Comment by timabbott** [comment]
We should probably split this into issues for the individual problems here :)

* https://github.com/zulip/zulip-android/issues/171 I think covers the first of your 3 issues.
* Opened https://github.com/zulip/zulip-android/issues/180 for your second issue.
* I opened https://github.com/zulip/zulip-android/issues/179 for a concrete take on resolving the third issue; we might also want to turn the problem with how the compose box is filled into a concrete behavior change we'd like to make.
