### ISSUE TITLE
App Not Marking My Place

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#167]
The app seems to lose track of how far down I've read.  If I close the app and come back to it, it starts me off at the same place that I was on last open, not at the newest unread messages.

**Comment by kenodoggy** [comment]
in progress

**Comment by kenodoggy** [comment]
Relates to [#170](https://github.com/zulip/zulip-android/issues/170)

**Comment by niftynei** [comment]
Duplicate of #181
