### ISSUE TITLE
Improve handling of compose box being at the bottom obscuring last message

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#171]
I've gotten a few complaints that the current compose box + bottom whitespace behavior can be quite annoying when you're at the bottom of the feed (i.e. fully caught up in whatever view you're looking at).  The problems are described as:

(1) An open compose box covers over the last message.
(2) Compose box is too annoying to close with swipe - maybe we should back the "back" button close it (rather the exiting the app) as well?

I think a reasonable solution to (1) is to add whitespace at the bottom of the feed just like we have in the Zulip webapp, so that the floating compose box does not cover over the most recent message.

**Comment by minervapanda** [comment]
I want to work for chat box improvisation.

**Comment by brainwane** [comment]
@minervapanda how is your progress going?

**Comment by niftynei** [comment]
in progress
