### ISSUE TITLE
Incoming messages do not reliably show up at bottom of home view feed

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#172]
I have a user report of multiple times new messages being sent (even sometimes sent by the current user) and not being correctly added at the bottom of the message feed (the message just never appears, even though other ones before and after do).  

This probably a priority bug to track down.

**Comment by timabbott** [comment]
(I received a screenshot from a user showing the issue, and I can confirm that a message that we clearly sent was missed in his feed)

**Comment by niftynei** [comment]
in progress
