### ISSUE TITLE
Avatars sometimes shown on green dots inconsistently

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#173]
It seems some users' avatars aren't being loaded properly in the Android app, and are displayed as a green presence dot, rather than the person's actual avatar, in the actual message feed.

E.g. for me, on zulip.tabbott.net, Sumana's avatar and my avatar don't show up, nor does Rishi's or GitHub Bot's, but everyone else has their avatar shown properly.  

If I had to guess, we had a network error when loading these avatars at some point, and incorrectly cached that "couldn't fetch the avatar" state permanently.  

(As a sidenote, I'm not sure why a green dot would be a good choice as the "couldn't fetch avatar" icon -- would be better to use something with the same form factor as our actual square avatars)

**Comment by brainwane** [comment]
@timabbott Would it be ok to break out the "better 'couldn't fetch avatar' icon" feature as its own issue?

**Comment by timabbott** [comment]
yes, that'd be totally reasonable.

**Comment by Sam1301** [comment]
Working on it :+1:

**Comment by niftynei** [comment]
The bug with avatars not showing up is a data model problem -- for some messages the sender details are not properly filled in. I'm investigating.
