### ISSUE TITLE
Improve behavior around compose box closing when scrolling

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#178]
Apparently, if you open the compose box via touching a message, and then scroll around, it doesn't close, but if you open it with the pencil icon and scroll around, it does.  

I think we probably want the scrolling behavior of closing the compose box to be consistent across different ways of opening it, BUT we want to have the compose box stay open in the event that the user has actually hand-written any text into it (whether it be a stream, topic or message body).  So I think we maybe just need to use a slightly different state machine for tracking whether the compose box should be closed.

**Comment by reached-ankita** [comment]
Hi! I would like to work on this bug.

**Comment by timabbott** [comment]
Go for it!

**Comment by brainwane** [comment]
Looking forward to your pull request, @reached-ankita! Please come visit us in https://zulip.tabbott.net/#narrow/stream/android if you're having any trouble submitting it. :)

**Comment by reached-ankita** [comment]
Hi! I made a pull request here ! https://github.com/zulip/zulip-android/pull/198
