### ISSUE TITLE
Update read flags and pointer when reading messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#181]
Logically:
- any message the user sees the entirety of should be being marked as read via the `POST messages/flags` endpoint.  
- If the user scrolls down in the home view, the latest message they saw in the home view, if newer than the user's pointer, should be submitted to the server as an update to the pointer via `PUT users/me/pointer`.

**Comment by Sam1301** [comment]
Hi, I'd like to work on this issue.

**Comment by brainwane** [comment]
Cool! @Sam1301 Go ahead. If you need any help, please speak up -- https://blogs.akamai.com/2013/10/you-must-try-and-then-you-must-ask.html might be a good guide. :)

**Comment by kunall17** [comment]
@timabbott 
File https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/networking/AsyncUnreadMessagesUpdate.java  uses the `messages/flags` endpoint and 

https://github.com/zulip/zulip-android/search?utf8=%E2%9C%93&q=updatePointer&type=Code uses the end point `users/me/pointer`

They are being updated I think, is there any problem?

**Comment by timabbott** [comment]
I've heard reports of there being a problem with this, but I think maybe the problem is that users who are not reading anything in the home view (and instead just look at narrows) don't end up updating the pointer on the server properly.  There's a server-side solution we need to do for that, so we can close this.

**Comment by Sam1301** [comment]
@timabbott @kunall17 I believe we are updating the pointer and read flags. Actually whats left is sync up with server for "read" messages (update_message_flags event) and updating the database accordingly which I have incorporated in my unread counts pr work. 
Should this be closed?

**Comment by timabbott** [comment]
Yeah, I think so.
