### ISSUE TITLE
App crashes on clicking on person's mention in message

### ISSUE THREAD

**Issue by Swati4star** [zulip/zulip-android#194]
After selecting a channel. If we click on some person's mention in the message, app crashes.

**Comment by brainwane** [comment]
Hi @Swati4star - thanks for reporting this. I'm sorry this is happening! Does this happen *every* time you tap on a message that @-mentions someone? And does it only happen with one person, or no matter who is being mentioned?

**Comment by Swati4star** [comment]
@brainwane Yes, on @-mentions someone 
Not on every person's name.
I saw app crashing on Tim Abbot's name.
Apart from him, I am checking for other persons.

**Comment by niftynei** [comment]
@Swati4star can you get a stack trace from logcat for this bug?  If you can get the app to crash, then run this command (you'll need to have the Android command line tools in your path for it to work):

`adb logcat -v time | grep AndroidRuntime`

**Comment by Swati4star** [comment]
@niftynei I tested the issue again.
It is not crashing on anyone's name right now.
It must have been fixed by some further commits :+1:
