### ISSUE TITLE
create new square fallback avatar for "couldn't fetch user's avatar" case

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-android#196]
As @timabbott said in #173:

> I'm not sure why a green dot would be a good choice as the "couldn't fetch avatar" icon -- would be better to use something with the same form factor as our actual square avatars

**Comment by Sam1301** [comment]
Hi, I'd like to work on this issue :)

**Comment by brainwane** [comment]
Great! Do you need any help to proceed, @Sam1301, or do you know what your next step is?

**Comment by Sam1301** [comment]
I don't know my next step yet, but I'd like to give it a try :D

**Comment by brainwane** [comment]
OK, @Sam1301 - I infer from what you've just said that you'd like some help. If I were you, I would use `git grep` to find places where the code mentions "Avatar" or "avatar", and use that to figure out what image is currently being shipped as the default avatar.

**Comment by Sam1301** [comment]
Thanks @brainwane :)

**Comment by Sam1301** [comment]
Hi, can I use this as the default image ? 
![default-image](https://cloud.githubusercontent.com/assets/14239866/19170347/a581db44-8c35-11e6-9aa7-033c42b051a2.png)
I created a new email account and obtained its hash to generate its unique gravator `identicon`.
https://en.gravatar.com/site/implement/images/

**Comment by timabbott** [comment]
yeah, that's probably a reasonable way to handle missing avatars.

**Comment by niftynei** [comment]
fixed in #199
