### ISSUE TITLE
Switch to gradle builds

### ISSUE THREAD

**Issue by bhaskarmurthy** [zulip/zulip-android#2]

**Comment by RX14** [comment]
:+1:

**Comment by RX14** [comment]
I have made preliminary work [here](https://github.com/RX14/zulip-android), but to be honest, I have never developed for android before and I have no idea what i'm doing... It builds though, no idea if it works, or if unit tests work, so I won't PR. Feel free to fork and improve, and PR.

**Comment by sv244** [comment]
+1

Wanted to open an issue about this myself. I'll look into it if I have some time.

**Comment by ibit** [comment]
[here] (https://github.com/ibit/zulip-android) is my take on the gradle migration.
Everything compiles.
* I didn't have the Crashlytics API key, so I've commented it out.
* Play services might not work. I used the latest.

**Comment by sv244** [comment]
The Crashlytics API key is in the AndroidManifest?

**Comment by AndyScherzinger** [comment]
@RX14 with my PR is basically the same thing as @ibit's Android-22, no Crashlytics (due to no key in place) but I bumped the minSdk to 13. So I guess any of the two should be fine.

**Comment by lfaraone** [comment]
Hey folks,

I want to thank @ibit , @ff-, @kosiara, @raicabogdan, and @kunall17 for their PRs, and apologize for the radio silence here :( 

I'm going to try to merge something that unbreaks master and incorporates the relevant fixes people contributed this week.

**Comment by lfaraone** [comment]
Done in ccb8836.

**Comment by timabbott** [comment]
Thanks for taking care of this Luke!!!
