### ISSUE TITLE
Absence of action bar experienced on device with Android version 4.4.2 in current app 

### ISSUE THREAD

**Issue by sashafierce** [zulip/zulip-android#206]
**Expected**

![expected](https://cloud.githubusercontent.com/assets/18103181/19275562/cdea57ae-8ff1-11e6-8dfd-dcb94a655cac.jpg)

**Action bar was missing on my device** 

![missing action bar](https://cloud.githubusercontent.com/assets/18103181/19275730/18ca0c74-8ff2-11e6-9488-ca8385602592.jpg)

**Comment by niftynei** [comment]
hi @sashafierce at times the bar disappears upward on scroll, can you verify for me that you never see the bar, even on app start?

**Comment by sashafierce** [comment]
Yeah it never appeared , not even once

**Comment by niftynei** [comment]
good to know. thanks for the report!

**Comment by sashafierce** [comment]
I checked on another device that was Android version 4.4.4 and the same issue was there right from the beginning

**Comment by sashafierce** [comment]
I would like to work on it myself if I may , Its been there for a while.  @niftynei

**Comment by timabbott** [comment]
@sashafierce go for it!

**Comment by sashafierce** [comment]
made a PR #284
