### ISSUE TITLE
Menu is not readable in Day Theme

### ISSUE THREAD

**Issue by rauladorean** [zulip/zulip-android#223]
The menu is not readable in Day Theme since the text is almost identical to the background
![p_20161024_123155_nt](https://cloud.githubusercontent.com/assets/15893975/19641442/5a6b2d1a-99e9-11e6-9a20-90e69a4b09e8.jpg)

**Comment by kunall17** [comment]
Can you tell us which android version are you using?

**Comment by rauladorean** [comment]
Hi,

My device is running on 4.4.2

**Comment by yadav-rahul** [comment]
@kunall17 I am facing similar issue in Android Version `4.1.2`

![device-2017-01-08-224850](https://cloud.githubusercontent.com/assets/15157620/21751889/c0542090-d5f4-11e6-8aeb-2272a2daf286.png)

`textColor` of menu items is not readable in day mode.

**Comment by rafidaslam** [comment]
I am facing this issue also on Android 4.4.2
![4](https://cloud.githubusercontent.com/assets/20320125/21763928/101d7e70-d693-11e6-8737-7f3c1892760f.png)

and yeah, like @yadav-rahul said, the menu items is not readable in day theme, it just readable in dark theme.
![z](https://cloud.githubusercontent.com/assets/20320125/21763980/5b687cea-d693-11e6-89ab-adaadfb496c7.png)

**Comment by yadav-rahul** [comment]
@Sam1301 @kunall17 I would like to solve this issue.

**Comment by kunall17** [comment]
@yadav-rahul go ahead! whats the update of the 3rd step of the star/unstar PR?

**Comment by yadav-rahul** [comment]
@kunall17 I am on it.

**Comment by kunall17** [comment]
Closed via #350
