### ISSUE TITLE
Stream name background color should be dark Grey in night mode 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#224]
The background color should be same as private messages header background color ![screenshot_20161024-152643](https://cloud.githubusercontent.com/assets/12700799/19641517/a6ebefca-99fe-11e6-99bf-b2baaf380882.png)

**Comment by saketkumar95** [comment]
Can i work on this?

**Comment by timabbott** [comment]
Sure!

**Comment by anuradhagupta345** [comment]
@saketkumar95 It's been long since you have taken this issue! Are you done with it?

**Comment by saketkumar95** [comment]
@anuradhagupta345 If you want then you can work on this. I totally forgot about this issue and i'm currently working on some other issues. :)

**Comment by rhari991** [comment]
@zulipbot claim-issue

**Comment by saketkumar95** [comment]
@timabbott @kunall17 we can close this i guess.

**Comment by Sam1301** [comment]
@saketkumar95 thanks, closing this issue.
