### ISSUE TITLE
"Failed to fetch Backends" 

### ISSUE THREAD

**Issue by jmandel** [zulip/zulip-android#227]
On the beta channel, when I try to enter a Zulip server URL (e.g. https://zulip.tabbott.net or https://chat.fhir.org) the value "/api/" is automatically appended, and then I get the error:

"Failed to fetch Backends" 

Is this a known issue?

**Comment by timabbott** [comment]
No; are you by any chance typing `http://` rather than `https://`?

**Comment by jmandel** [comment]
No, though I did try that for fun, and I get a security popup asking whether I really wanted to use HTTP (and saying "yes" led to the same error).

**Comment by timabbott** [comment]
Interesting.  @niftynei any idea what in the beta could have caused this?  It's not a big diff from the production release...

**Comment by jmandel** [comment]
BTW is there an easy way for me to test the production release (move off the beta channel)? Alternatively, can anyone report whether they can reproduce this behavior (in beta or prod)?

**Comment by timabbott** [comment]
I can't reproduce with 1.1.1 (the beta)

**Comment by kunall17** [comment]
Production release is at this branch https://github.com/zulip/zulip-android/tree/release-candidate
I also use the beta app and it works fine!

**Comment by jmandel** [comment]
It appears that the android client relies on `/api/v1/get_auth_backends` (introduced [here](https://github.com/zulip/zulip/commit/a36e5d4987d9ac8128c57dab4e5c42ded175f304)), and https://chat.fhir.org is running a version of Zulip old enough not to have one.

But that's not the whole issue, because I get the same error message for https://zulip.tabbott.net, which *does* have one.

**Comment by niftynei** [comment]
thanks for the report. fwiw the error message you're receiving isn't very precise.  a failure to get backends may happen for a variety of reasons, including a network failure.  can you verify that you're able to reach the website on a different app?

**Comment by jmandel** [comment]
To confirm, yes, I can reach these sites through the browser just fine. Is that what you mean,  @niftynei?

**Comment by timabbott** [comment]
Does https://chat.zulip.org work for you as an Android auth point?  I wonder if the old zulip.tabbott.net name is what's busted.

**Comment by jmandel** [comment]
No, https://chat.zulip.org/ also fails, with the same error. For what it's
worth, everything was working just fine until I signed out and tried to
sign back in to demonstrate the process for a colleague..

**Comment by timabbott** [comment]
Oh, that detail is interesting.  I wonder if it's some sort of caching bug...

**Comment by jmandel** [comment]
Progress: this problem persisted across uninstalling and reinstalling (both beta and default channel). But creating a new user account on my Android device and installing within that account... there, everything works (even talking to chat.fhir.org, which puzzles me, given that the `get_auth_backends` endpoint does not exist there).

**Comment by jmandel** [comment]
Back on mystery original account: using Android app settings to clear data + cache for Zulip had no effect. Repeating that process a second time did have an effect, but now I see:

1. Select chat.fhir.org 
2. Choose Google as my identity provider 
3. Complete the sign-in flow
4. I'm signed into chat.zulip.org instead of chat.fhir.org (!!) 

If I choose the username+password login flow, I  get a "Your username or password is incorrect" error (when it's not). 

One other small issue: when I paste in a url like `chat.fhir.org ` with a trailing space, this confuses the operation that appends `/api` to the endpoint (the space is preserved) and causes an exclamation mark icon (with no text or explanation) to appear next to the server url... but only after I enter a password.

**Comment by timabbott** [comment]
Thanks for doing all that debugging @jmandel!  It sounds like we have something interesting going on here that is causing it to try connecting to chat.zulip.org regardless of what server you specify.

As a sidenote, I don't think we need the `/api`  in the URI to be user-facing; it can be appended in the code when it makes the requests.  Since the old api.zulip.com doesn't exist anymore, the app can just plan to unconditionally append `/api` to the server URI to figure out the API URI.  

@Sam1301 do you have time to  to debug this?  This is a serious issue that we should prioritize.

**Comment by Sam1301** [comment]
Sure, working on this :+1:

**Comment by Sam1301** [comment]
Submitted a pr for the same :+1:

**Comment by maxlinux2000** [comment]
HI, I'm trying with my own zulip server (1.4.2) and I just build the last version of the android client, but as you can see below the error still here

![photo759931202910136346](https://cloud.githubusercontent.com/assets/5683921/21261573/a315ee84-c38c-11e6-8082-0b63f33217b5.jpg)
