### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-android#231]
**Actual Behaviour**

As of now when someone opens app in landscape mode some info(Legal Information) is not visible on screen due to lack of scroll.

**Expected Behaviour**

It should scroll, so user can see whole info.

**Steps to reproduce it**

Add ScrollView as parent in login.xml

**Screenshots of the issue**

![whatsapp image 2016-12-01 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/21558765/20788669/bdf7524e-b7d7-11e6-95a6-ea8a175ea894.jpeg)

Can i work on this @timabbott @kunall17

**Comment by kunall17** [comment]
Sure, do checkout this similar (or rather same open issue) https://github.com/zulip/zulip-android/issues/151

**Comment by saketkumar95** [comment]
okay. i will be sending the PR soon on scrolling issue.

**Comment by saketkumar95** [comment]
closed by [#235](https://github.com/zulip/zulip-android/pull/235)
