### ISSUE TITLE
Quality Assurance: App crashes when pinging users with '@'

### ISSUE THREAD

**Issue by derAnfaenger** [zulip/zulip-android#233]
The Android app crashes when I try to ping a user in a message with '@'. More specifically, it crashes when typing the first letter after the '@'.

**Comment by timabbott** [comment]
@Sam1301 this seems likely to be a bug one can fix relatively quickly...

**Comment by Sam1301** [comment]
@derAnfaenger thanks for reporting this! I couldn't reproduce this error. Can you provide with more details as to when this error occurs? When I tried to click on a user, the app didn't crash.

**Comment by derAnfaenger** [comment]
@Sam1301 
This happens for the production build on my phone, version 1.1.0
1. Open the app.
2. Tap the pen icon in the lower left corner.
3. Tap the message box (where it says "Tap on a message to compose reply").
4. Enter '@', followed by some letter.
5. The app should crash.

**Comment by Sam1301** [comment]
Thanks @derAnfaenger  for reporting this bug. Submitted a pr for the same :+1:
