### ISSUE TITLE
New Feature: Add search option in stream and people list

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#237]
**Current**
If Stream and people list is large enough, then it is difficult to get desired item (scroll so much to go down).

**Better option**
Add `EditText` in the `drawer` and on text change filter the `listview`.

I would like to work on this.

**Comment by vishwesh3** [comment]
@kunall17 @timabbott . Please review it.

**Comment by brainwane** [comment]
Hi @vishwesh3 - could you help us understand what you're asking them to review? Have you made a pull request already, or are you asking us to review your request for permission to work on this issue?

**Comment by vishwesh3** [comment]
@brainwane I was asking for permission to work on this. After the discussion with @kunall17 I have started working on this. Will be creating PR soon. Thanks

**Comment by timabbott** [comment]
Closing this since it was just merged; @vishwesh3 in the future you can put `Fixes: #237` in the last commit message in the PR to have it be closed when the PR is merged.

**Comment by vishwesh3** [comment]
@timabbott thanks. Will keep in mind about commit message next time.
