### ISSUE TITLE
Add Splash Screen in the app

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-android#239]
Currently there is no splash screen in the app. I would like to implement this feature in the app.

@kunall17 @timabbott Can i work on this?

**Comment by kunall17** [comment]
There is no need of splash screen as initially we need to enter the server URL and that loginActivity loads pretty fast! 
This issue was posted previously as well https://github.com/zulip/zulip-android/issues/164

**Comment by saketkumar95** [comment]
Cool. Closing then. :)

**Comment by saketkumar95** [comment]
@kunall17 If user is logged in and  closes the app for some time and reopens it then on HomeView he/she gets to see that loading messages progress bar. We can have a splash screen and use this time for displaying messages. What do you think about this??

**Comment by kunall17** [comment]
Na, its fine with the loading messages, how about working with showing cached messages while loading?

**Comment by kunall17** [comment]
This issue can be closed!
