### ISSUE TITLE
Zulip Android has been Converted to a Gradle Project (Android Studio)

### ISSUE THREAD

**Issue by MarkCupitt** [zulip/zulip-android#24]
Check out https://github.com/MarkCupitt/zulip-android-gradle/

Also added server url on login screen to mimick iOS

There is a debug APk in the APK Dir to try

**Comment by sujaysudheenda** [comment]
Are you currently working on this issue? will be able to complete this soon? just curious since I was trying to build zulip on android studio and was not able to succeed if this issue will be solved soon then it would greatly help :)

**Comment by lfaraone** [comment]
Dup of #2
