### ISSUE TITLE
Can't login from the app

### ISSUE THREAD

**Issue by maxlinux2000** [zulip/zulip-android#242]
Hi

I have finally installed my server in a VPS on digitalocean, and I can login from the web UI.

Now I have downloaded the android app from playstore and inserted the the fields:

My server name (FQDN over https)  
my user admin name
my passwd

...but the app tell me that the passwd is wrong
So I tried with another user, without success again.

Witch log can I look, in order to understand the problem that stop me to user the android app?

regards
MaX

**Comment by Sam1301** [comment]
Hi @maxlinux2000. Did you try to kill the app by opening recent apps menu and then starting again? There is an ongoing issue #227 which might have caused some incorrect caching of server url.

**Comment by timabbott** [comment]
We just pushed a new release (1.1.2) with the fix to #227 in it; @maxlinux2000 once you upgrade, can you let us know if you still see this problem?

**Comment by maxlinux2000** [comment]
sorry but I'm just arrive to zulip....
The server is the version 1.4.2
the app from playstore il the 0.0.3

I tried to compile the zulip-android without android-studio, using ./gradlew, but it fail with the following error:

`* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'fabricKey' for project ':app' of type org.gradle.api.Project.
`
Following the readme I see that the files:
app/src/main/java/com/zulip/android/ZLog.java
and 
app/src/main/java/com/zulip/android/ZulipActivity.java
are missing so I tried to compile it without success

Then I commented all references to "crashlytics", but the compilation still resist to me showing same error.

any idea?

regards
MaX

**Comment by Sam1301** [comment]
Hi @maxlinux2000  you can remove the fabricKey error by following these steps:
 1)  Create a file named gradle.properties in the app directory of the project.
 2) Add a line fabricKey=blah in it.
 3)  Sync project with gradle files.
Also, the server version and app playstore version need not match. You can still download the latest version of the app from playstore and try running it to see if the error persists.
Thanks

**Comment by maxlinux2000** [comment]
finally the app is compiled and running in my phone... but the error #227 still occurs

![photo759931202910136345](https://cloud.githubusercontent.com/assets/5683921/21261399/6c63f92c-c38b-11e6-821d-8fd98234a02f.jpg)

**Comment by Sam1301** [comment]
@maxlinux2000 Did you update the app?

**Comment by maxlinux2000** [comment]
ok.... I understand the  my error... I need to insert the email address instead the username.

sorry for the trouble

**Comment by timabbott** [comment]
@Sam1301 it may be worth giving a special error message for users who don't include an `@` in their email?  

Since with things like LDAP support, we may allow users to just type a username (without domain) in the future, I'd probably just modify the error message on login failure in the case that (1) there's no @ in the email and (2) that LDAP feature is not enabled.

Since this error message comes from the server, this is a server-side change; if this idea makes sense to you, can you open an issue on zulip/zulip for improving the error message?  Thanks @Sam1301!

**Comment by maxlinux2000** [comment]
We need to modify the message in the string.xml too, from: 
"Your username or password is incorrect" -> " Your email or password is incorrect"

**Comment by timabbott** [comment]
Is that string actually in string.xml?  I had been assuming we were just displaying an error message coming from the server.

**Comment by Sam1301** [comment]
The error comes from the server, will open an issue in zulip/zulip for it :+1:

**Comment by Sam1301** [comment]
Submitted :+1:
