### ISSUE TITLE
Clicking on an uploaded image causes it to open in a browser

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#243]
We should probably instead open it in a lightbox in-app, similar to how we handle this on web.

**Comment by saketkumar95** [comment]
Can i work upon this?

**Comment by timabbott** [comment]
Sure!  There's probably at least 2 cases to test:
* image uploaded
* link to image with inline preview

**Comment by anuradhagupta345** [comment]
@saketkumar95 What is your progress on this one?

**Comment by timabbott** [comment]
@anuradhagupta345 if you'd like to help with this, it looks like https://github.com/zulip/zulip-android/pull/286 is open and waiting for feedback; can you give that a test and post feedback?
