### ISSUE TITLE
Upgrade to Firebase Cloud Messaging

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#245]
Since it appears we can upgrade the client without changing the server, we might as well take care of the client-side upgrade early (since we can't really migrate the server until all clients in use are upgraded).

**Comment by sashafierce** [comment]
I would like to work on this ,I have worked with firebase though I'd need some guiding.

**Comment by noone1337** [comment]
@timabbott 
Is it on you screen that Google deprecated GCM in April 2018 and it will be shutdown on April 11th, 2019. 

https://android-developers.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html
> The GCM server and client APIs have been deprecated and will be removed as soon as April 11th, 2019

https://developers.google.com/cloud-messaging/ also shows a red notice
> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019.

**Comment by timabbott** [comment]
@noone1337 this repository is stale, for a desupported dead version of the app.  Closing as this has already been fixed for zulip/zulip-mobile, the active app.
