### ISSUE TITLE
Don't open the keyboard immediately on email/password login page

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#246]
Since on Android, Google auth is usually going to be what folks want, we should probably not open the keyboard immediately (since it sorta obscures the Google auth button) and require users to click into the text boxes to start typing.  What do you think @kunall17?

**Comment by saketkumar95** [comment]
@timabbott we can do so just by implementing callback methods from the KeyEvent.Callback interface, such as onKeyDown() and onKeyMultiple().

**Comment by kunall17** [comment]
Yeah, we should do that! 
@saketkumar95 can you test this and send a PR for this one? 
 The manifest edit is the better approach!

**Comment by saketkumar95** [comment]
Yes. Sure . i will send the PR by morning today.
