### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by anirudhjain75** [zulip/zulip-android#247]
## Steps to verify the bug ##
* Choose any **stream**.
* Scroll down to till you reach the **end**.
* Tap the screen to invoke the write option.
* It does not get invoked.
* For getting it invoked you'll have to scroll bit up.

**Comment by anirudhjain75** [comment]
![screenshot_20161215-234841](https://cloud.githubusercontent.com/assets/14249589/21259497/b51e6a0a-c3a7-11e6-8542-35bf3fea8c65.png)

**Comment by sonali0901** [comment]
@anirudhjain75  I invested this bug report. If you go till the end of any stream and tap anywhere on the whitespace area (below the message feed that is not a part of the scroll bar area as you reported earlier, but is intentionally left as said by Tim) then yes, the write option is not invoked. But if you tap on the message feed area(even when you are at the end of a stream) the write option is invoked. There is no need to scroll up. Our concrete motive of having the ability to access writing feature at the end of any stream is satisfied. Maybe you want to re-frame this bug or find a new one.
