### ISSUE TITLE
Register new account

### ISSUE THREAD

**Issue by maxlinux2000** [zulip/zulip-android#249]
It would be nice if the user can create a new account from zulip-android

**Comment by timabbott** [comment]
Agreed.  It's kinda expensive to maintain 2 copies of the registration flow; we might just want to provide a nicely integrated way to get to that flow from the Android app; I guess this would need to be a link from the page after you choose your server.

**Comment by kunall17** [comment]
@timabbott for this one, we could just add a link after entering the server and open the browser in a chrome custom tabs? 
Now after registration, user can manually enter credentials.
A better (but far more complex) would be deeplinking the android project which would send an API key to the android client after registration, and use this key to login?

**Comment by timabbott** [comment]
Yep.  Let's do the v1 with the browser and then we can try to figure out how to deeplink as a potential followup.

**Comment by vishwesh3** [comment]
I would like to work on this.

**Comment by kunall17** [comment]
@vishwesh3 sure go ahead, with the first step!
