### ISSUE TITLE
[Quality Assurance] Zulip app doesn't alerts user about stream name is invalid when user input a "similar" stream name

### ISSUE THREAD

**Issue by rafidaslam** [zulip/zulip-android#255]
When inputting a "similar" but invalid stream name, Zulip doesn't warn user about that stream name is invalid.

How to reproduce this issue:

1. Go to Zulip and login to a server.
2. Then see at the "Stream" list and note the stream name that has space, like "GCI general"
![3](https://cloud.githubusercontent.com/assets/20320125/21361951/d3aa4588-c718-11e6-904a-60cb13a7ac44.png)

3. Write the first stream name (the first word of the stream name) in stream input box.
4. Then write topic and a message.
5. Then send the message.
6. It will be returns "Error sending message".
![4](https://cloud.githubusercontent.com/assets/20320125/21361990/02847360-c719-11e6-8b92-f0718a459a40.png)

As expected Zulip need to return a message that sounds like "Stream does not exist", but here Zulip didn't return that.
![1](https://cloud.githubusercontent.com/assets/20320125/21362029/335c776c-c719-11e6-8b5f-9150c7cbf711.png)

**Comment by vishwesh3** [comment]
Hi if this issue is not assigned to anyone I would like to work on this.
