### ISSUE TITLE
[Quality Assurance] Zulip App let user send message to the stream that they're not subscribed

### ISSUE THREAD

**Issue by rafidaslam** [zulip/zulip-android#256]
When using Zulip, and fill the "Stream" textbox with the stream name that's we're not subscribed. Zulip let user sends the message to that stream.

How to reproduce:

1. Go to Zulip and login to a server.
2. Then type the stream name that's exist but we're not subscribed yet in the "Stream" textbox. Here my Zulip account isn't subscribed to "test" stream.
3. Type the topic and message.
4. Then send the message.
![2](https://cloud.githubusercontent.com/assets/20320125/21362810/7b2b3454-c71c-11e6-9d84-e630a0cfbdf2.png)

Zulip app will returns *Message sent!* , and I can confirm that message is sent to that stream by accessing https://chat.zulip.org/#narrow/stream/test
![screenshot from 2016-12-21 01-33-21](https://cloud.githubusercontent.com/assets/20320125/21363073/a029a2bc-c71d-11e6-8274-2df6c38908d7.png)

Meanwhile when I try it in Zulip web:
![screenshot from 2016-12-21 01-28-59](https://cloud.githubusercontent.com/assets/20320125/21362985/38868b0c-c71d-11e6-9394-c57ea31a71d2.png)

**Comment by kunall17** [comment]
Thanks for reporting this! :)

**Comment by vishwesh3** [comment]
@kunall17 if this issue is not assigned to anyone then assign this to me, I would love to work on this.

**Comment by kunall17** [comment]
@vishwesh3 :+1:

**Comment by vishwesh3** [comment]
This is fixes in PR  https://github.com/zulip/zulip-android/pull/259 and can be closed.

**Comment by timabbott** [comment]
Thanks @vishwesh3, closing :)
