### ISSUE TITLE
Server connection Error message should provide more context

### ISSUE THREAD

**Issue by IffatTix** [zulip/zulip-android#258]
On trying to connect to the server through the app, error message should provide more context instead of just saying "Failed to fetch backends"

**Comment by timabbott** [comment]
I think we should make this say something like "Unable to connect to server %s; did you spell it correctly?", filling in the server name they typed.

**Comment by IffatTix** [comment]
In case of typos in the name yes! Do we have a different message just in case actual server is unreachable?

**Comment by kunall17** [comment]
We can show custom messages when 
- Not connected to internet
- Server doesn't exists on that URL
- Text written there is not a valid URL

**Comment by saketkumar95** [comment]
@timabbott @kunall17 Can i fix this issue?

**Comment by kunall17** [comment]
@saketkumar95 :+1:
