### ISSUE TITLE
User list discrepancies between Android and Web Zulip

### ISSUE THREAD

**Issue by 540KJ** [zulip/zulip-android#262]
Differences in who's online, inactive or disconnected between android app and web zulip. This may be an issue for large teams. Also posted [here](https://github.com/zulip/zulip/issues/2877) on the main Zulip issues list:
<img src="https://cloud.githubusercontent.com/assets/23611943/21445534/757977d4-c90e-11e6-9b73-7d13feca6093.png" width="225" height="400" />
<img src="https://cloud.githubusercontent.com/assets/23611943/21445535/758693b0-c90e-11e6-85c3-2acd7e4e9b17.PNG" width="175" height="400" />

**Comment by vishwesh3** [comment]
I think we should do it via GCM and android service. On app launch start a service which will mark user status as online on the server and stops service as soon as app is closed. And through GCM we can update the list of status in local database.

**Comment by timabbott** [comment]
@vishwesh3 first you should look at how we do this already; I think much of that implementation idea is already present, with the exception of the GCM piece (which I think is unnecessary; our API endpoint for status returns the status of everyone else in the response to submitting one's own status).

**Comment by timabbott** [comment]
But I think there is probably a bug here in the Android app's implementation that is it showing laggy data (or something).

**Comment by vishwesh3** [comment]
I would like to work on this.

**Comment by anuradhagupta345** [comment]
@timabbott I would like to resolve this issue(if not done yet)

**Comment by vishwesh3** [comment]
@anuradhagupta345 I am working on this. Thanks for your interest :)

**Comment by kunall17** [comment]
How about we display the online users and after that the users which we have previously chatted with and after that alphabetically order them?

**Comment by yadav-rahul** [comment]
@kunall17 It will be nice but I have one query. How will preciously chatted users be shown? I mean whether they will be shown alphabetically or in decreasing order of chat messages shared between them or the most recent ones on the top.

**Comment by vishwesh3** [comment]
Yes It will be nice and will increase user private messaging experience. We can get user recent PM from messages table and sort the list according (online <-> recent chats <-> other in alphabetically ascending).
Will create a PR soon . :)

**Comment by kunall17** [comment]
@yadav-rahul most recent chatted with order!

**Comment by vishwesh3** [comment]
Done now list is sorted like this

Recent chat was done with Zoe so it is above lago.
![zulip people sort](https://cloud.githubusercontent.com/assets/18511177/21808982/baf17d46-d76b-11e6-95e2-c60ed4b21fd1.png)

I was thinking adding a small text heading above each group (Online, Recent, Others) in the above list.
@kunall17 What you you think?

**Comment by vishwesh3** [comment]
While working on this I encounter one more issue
**Steps to reproduce**
Open people drawer -> Select **All Private messages** -> Wait until messages are loaded -> Again open People Drawer -> List of people is reduced -> Again come to home -> List is still reduced

**Expected Behavior**
List should not be reduced.

In my case List does not contain that person to whom I have done some private messages.
 
![videotogif_2017 01 11_22 37 54](https://cloud.githubusercontent.com/assets/18511177/21858477/447eba68-d84f-11e6-8844-cb42ecdc8e22.gif)

**Comment by Sam1301** [comment]
Cool! @vishwesh3 can you please claim this task? That way it'd be easy for other contributors to skip through unassigned issues :)
