### ISSUE TITLE
Switch between hide and view password in LoginActivity

### ISSUE THREAD

**Issue by saketkumar95** [zulip/zulip-android#263]
Currently there is no option to view the password whenever it is entered. There should be an option to view the password which is entered.

@timabbott @kunall17 Can i work on this? This is a very small issue. Will send the PR soon.

**Comment by kunall17** [comment]
@saketkumar95 :+1:

**Comment by saketkumar95** [comment]
Closed https://github.com/zulip/zulip-android/pull/266
