### ISSUE TITLE
"Today" option in menu

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#264]
"Today" option in menu is not required if **Today Message** page is already opened. We can either remove that or add other filter options like **Yestarday** etc .

![videotogif_2016 12 27_00 58 57](https://cloud.githubusercontent.com/assets/18511177/21485927/5d013dd4-cbd1-11e6-9d56-50f6ddd4fdb9.gif)

@timabbott @kunall17 @Sam1301 Can I work on this?

**Comment by kunall17** [comment]
Maybe a option like One day before, and let it go in a loop like if we go Today -> One day before -> One day before -> One day before
It would be an easy task, you need to tinker with the NarrowToday filter!

**Comment by vishwesh3** [comment]
Thanks @kunall17 I will send PR soon.
