### ISSUE TITLE
Text in searchView not cleared on BackPressed

### ISSUE THREAD

**Issue by nitish1211** [zulip/zulip-android#267]
Once a search is performed on the chat screen and we press back to get back to the chat screen from the search results, the text in the searchView is still there and is not cleared and replaced by the action bar.

![g_20161228_0406314](https://cloud.githubusercontent.com/assets/13676490/21510216/e198d1e8-ccb6-11e6-84e2-538d06180815.gif)

I think the searchView should clear and the Action bar should take its place. Something like this:

![g_20161228_0427014](https://cloud.githubusercontent.com/assets/13676490/21510255/3e058520-ccb7-11e6-9726-ac16398028d9.gif)

  @kunall17 @timabbott  I would like to make this improvement in the app.

**Comment by nitish1211** [comment]
So should I create a PR for this ?

**Comment by kunall17** [comment]
@nitish1211 Yeah, go ahead..:+1:
