### ISSUE TITLE
Markdown not displaying.

### ISSUE THREAD

**Issue by 540KJ** [zulip/zulip-android#272]
Markdown for strikethroughs, code and tables aren't displaying in app. Also some language scripts aren't displaying that well. Any way to fix this in Android?
Markdown Code:
<img src="https://cloud.githubusercontent.com/assets/23611943/21571727/148a1722-ce76-11e6-8cdc-ea9dd3494bac.png" width="225" height="400" />
Markdown Tables:
<img src="https://cloud.githubusercontent.com/assets/23611943/21571728/148aac32-ce76-11e6-9a1b-9af8ec72d233.png" width="225" height="400" />
Language Scripts:
<img src="https://cloud.githubusercontent.com/assets/23611943/21571726/148a14ca-ce76-11e6-8e6e-b1e2e602805f.png" width="225" height="400" />
Web versions:
![markdown code-web](https://cloud.githubusercontent.com/assets/23611943/21571753/64df4828-ce76-11e6-87a6-29eaf2307908.PNG)
![markdown scripts-web](https://cloud.githubusercontent.com/assets/23611943/21571754/64e108fc-ce76-11e6-89dc-ef159676b8ce.PNG)
![markdown table - web](https://cloud.githubusercontent.com/assets/23611943/21571755/64e27a52-ce76-11e6-9899-0ab60a5f016e.PNG)

**Comment by timabbott** [comment]
It'd be awesome to fix these issues.

**Comment by Sam1301** [comment]
I would like to work on this :)

**Comment by anuradhagupta345** [comment]
@Sam1301 Are you done with this issue?

**Comment by Sam1301** [comment]
Hi @anuradhagupta345, I am currently working on other issues. Till such time if you can work on this issue, it'd be great :)

**Comment by anuradhagupta345** [comment]
@Sam1301 I will be sending PR soon for this issue!

**Comment by kunall17** [comment]
Fixed via #371
