### ISSUE TITLE
Multi platform app (iOS, WinPhone, Android, etc)

### ISSUE THREAD

**Issue by web-mi** [zulip/zulip-android#28]
Hi,

i already started working on a AngularJS app with phonegap because i don't think a native app for each platform is needed and brings a huge workload for a open source project.
Because it's my first app i already tried to upload the app to the store and on windows phone (haven't tried if it works currently because i have no phone available) and android its already available. iOS is in progress but as i read it needs up to 14 days to get verified.
You could find the code here (https://github.com/web-mi/Zulip-Messenger).
I will progress on the app because its my first app and some things have to be fixed.
Some constructive feedback would be great!

Cheers
Marc

**Comment by niftynei** [comment]
Hey Marc, thanks for the note about the AngularJS project you're working on.  Zulip's got an active (google-group)[https://groups.google.com/forum/#!forum/zulip-devel] that's a great place for this kind of announcement (sorry, I don't know JS!)
