### ISSUE TITLE
Small UI bug in textColor of EditText

### ISSUE THREAD

**Issue by yadav-rahul** [zulip/zulip-android#287]
**Actual Behaviour**
While searching for people in night theme, `textColor` of EditText is white by default:

![giphy 1](https://cloud.githubusercontent.com/assets/15157620/21751354/d22fcb9c-d5eb-11e6-86e3-3e606e6ef0e5.gif)

**Expected Behaviour**

![giphy](https://cloud.githubusercontent.com/assets/15157620/21751389/5b2756fe-d5ec-11e6-9b8e-8574c52e66fe.gif)

@timabbott @kunall17 Shall I make PR for this?

**Comment by timabbott** [comment]
Sure!
