### ISSUE TITLE
DrawerLayout is not auto closing

### ISSUE THREAD

**Issue by yadav-rahul** [zulip/zulip-android#288]
Currently drawer is not closing itself by clicking an item of `ExpandableListView`:

![giphy 2](https://cloud.githubusercontent.com/assets/15157620/21751602/d8bf1400-d5ef-11e6-81dd-2bb4868c8cf6.gif)

Whereas it should hide as soon as click is made on an item.

@kunall17 @timabbott What are your views on it?

**Comment by timabbott** [comment]
Sounds like a regression to me.

**Comment by saketkumar95** [comment]
StreamDrawer is a expandable listView and this should remain expanded so that user can select the topics. It's already fixed https://github.com/zulip/zulip-android/pull/195 here and extended issue is fixed here https://github.com/zulip/zulip-android/pull/254

Kindly go through all the PRs and issues before creating one.And Correct me if i'm missing something or wrong. :)

**Comment by yadav-rahul** [comment]
@saketkumar95 I went through all issues and pulls before contributing. What I thought was, till StreamDrawer bug is fixed auto closing ExpandableListView would be a better option because it was looking kind of weird (since ExpandableListView was not expanding). 

Also soon after this, I was planning to make a new PR which would eventually fix `StreamDrawer` issue and will auto-close drawer layout too by clicking on a particular topic of a stream.

**Comment by saketkumar95** [comment]
@yadav-rahul It's been fixed here https://github.com/zulip/zulip-android/pull/195 and https://github.com/zulip/zulip-android/pull/254 here. I don't know why it's not merged. 

@kunall17 Is there something more left ??

**Comment by kunall17** [comment]
Yup, well this might seem confusing but when the expandableListView bug is fixed it wouldn't be confusing! 
Btw if you click directly on the textView of the stream name the drawer will close!

**Comment by kunall17** [comment]
Also i forgot to mention in the comment above, this is not a bug and can be closed, this is how the streamsDrawer is supposed to work!

**Comment by yadav-rahul** [comment]
Thanks @kunall17 for clearing this out. I am closing this issue then.
