### ISSUE TITLE
Add message editing feature

### ISSUE THREAD

**Issue by anuradhagupta345** [zulip/zulip-android#290]
Once a message is sent there is no way one can change it. What about adding a delete feature in app which will delete a message sent?

**Comment by timabbott** [comment]
@anuradhagupta345 Zulip doesn't support deleting messages, and we don't really intend to for various UI reasons (it's confusing, gives a false sense of security, and encourages people to build loggers to record the messages anyway).  I think it would be reasonable to add a message editing UI to the Android app; that feature has been present on web for years.

**Comment by ShailyTyagi** [comment]
Hi! I am new to contributing to open source and i would love to start off by working on this issue.@timabbott

**Comment by yadav-rahul** [comment]
@timabbott I would like to work on this.

**Comment by kunall17** [comment]
@yadav-rahul go ahead
Suggestion: Add an option in the long press menu of the contentView and on this option press opens up a dialog to edit the text! 
And this editing feature is only allowed within 30 mins (or 10 mins not sure, check on the web UI) when the message is sent!

**Comment by timabbott** [comment]
Just a quick note: the 30m window is a realm configuration setting; for some realms, edited is allowed forever.

**Comment by yadav-rahul** [comment]
Thanks @timabbott for notifying about this. Between I am done with this issue and will send a PR soon :)

**Comment by anuradhagupta345** [comment]
@kunall17 @timabbott Shall I work on this?

**Comment by yadav-rahul** [comment]
@anuradhagupta345 I've already sent a PR for this. Please see #300.
