### ISSUE TITLE
Android emoji input leads to display problem

### ISSUE THREAD

**Issue by brainwane** [zulip/zulip-android#299]
I have just downloaded the Android app from the Google Play store to a phone running Android 7.0.

When I use the `:name-of-emoji:` syntax when composing a message in the Android app, the emoji displays properly in the app; when I use the autocomplete my OS gives me to choose an emoji, the emoji does not display. See the screenshots here, demonstrating the different Android and desktop displays of [this thread](https://chat.zulip.org/#narrow/stream/test.20here/subject/Android/near/126504).

![zulip-emoji-display-android-not-ok](https://cloud.githubusercontent.com/assets/842790/21917110/5046d83e-d913-11e6-8cde-724ed03f720a.png)
![zulip-emoji-display-ok](https://cloud.githubusercontent.com/assets/842790/21917109/504685a0-d913-11e6-8612-c340e43d8b15.png)

Might be related to #13.

**Comment by Sam1301** [comment]
@brainwane Thanks for reporting this error. I guess the paths are not being processed correctly. I have tried to solve this bug using #285 . Can you please try this and let me know if this solves the issue? Thanks :)
