### ISSUE TITLE
Can't build app from source 

### ISSUE THREAD

**Issue by Macbet2** [zulip/zulip-android#3]
When i try build app from source i get this errors
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 46 source files to C:\Users\username\Desktop\zulip-android\bi
n\classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed
in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use
-Xlint:-options.
    [javac] C:\Users\username\Desktop\zulip-android\src\com\zulip\android\LoginActi
vity.java:25: error: package com.google.android.gms.common.GooglePlayServicesCli
ent does not exist
    [javac] import com.google.android.gms.common.GooglePlayServicesClient.OnConn
ectionFailedListener;
    [javac]                                                              ^
    [javac] C:\Users\username\Desktop\zulip-android\src\com\zulip\android\LoginActi
vity.java:30: error: cannot find symbol
    [javac]         OnConnectionFailedListener {
    [javac]         ^
    [javac]   symbol: class OnConnectionFailedListener
    [javac] C:\Users\username\Desktop\zulip-android\src\com\zulip\android\LoginActi
vity.java:123: error: method does not override or implement a method from a supe
rtype
    [javac]     @Override
    [javac]     ^
    [javac] Note: C:\Users\username\Desktop\zulip-android\src\com\zulip\android\Cus
tomHtmlToSpannedConverter.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 3 warnings

BUILD FAILED
E:\android-sdk\tools\ant\build.xml:716: The following error occurred while execu
ting this line:
E:\android-sdk\tools\ant\build.xml:730: Compile failed; see the compiler error o
utput for details.

Total time: 14 seconds

**Comment by sv244** [comment]
You're missing a library.

**Comment by Macbet2** [comment]
yeah i change google-play-services target to android-20 ant build app

**Comment by lfaraone** [comment]
Since this app hasn't (yet) been moved to gradle, and whatever issues here will be hopefully fixed when that lands, closing.
