### ISSUE TITLE
Navigation Drawer doesnt close automatically on click

### ISSUE THREAD

**Issue by nitish1211** [zulip/zulip-android#304]
The Navigation drawer does not close when a channel is selected. I think the UX would be much better if it did.

![1](https://cloud.githubusercontent.com/assets/13676490/22031212/04c1f032-dd06-11e6-81f5-70f48fbdde2c.gif)

It has been implemented in the private chat list.

![2](https://cloud.githubusercontent.com/assets/13676490/22031391/867a36fc-dd06-11e6-973e-7f634d063d50.gif)

Also when the Nav drawer is open pressing the back button should close the drawer.

@kunall17 @timabbott I would like to work on implementing this UX improvement.

**Comment by saketkumar95** [comment]
Kindly check https://github.com/zulip/zulip-android/issues/288

**Comment by vishwesh3** [comment]
Thanks @nitish1211 for reporting.
Actually on selecting stream it should expand and show list of topic of that stream (like in web). PR have been created for that and are under review.
https://github.com/zulip/zulip-android/issues/288
PR https://github.com/zulip/zulip-android/pull/283

**Comment by nitish1211** [comment]
Thanks for the references @saketkumar95 @vishwesh3  I'll close this then.
