### ISSUE TITLE
Scrolling after reaching end of message list still displays 'Loading Messages' progress bar.

### ISSUE THREAD

**Issue by sashafierce** [zulip/zulip-android#305]
Recycler view shows 'Loading Messages' progress bar even after reaching the last message of a given stream every time list is scrolled which gives the feeling that some messages are yet to be loaded.

<img src=https://cloud.githubusercontent.com/assets/18103181/22038295/944661ce-dd20-11e6-8e11-8dc6bb0079e7.png width=300 height=500 />

<img src=https://cloud.githubusercontent.com/assets/18103181/22037297/a695a064-dd1c-11e6-9caa-871bf5f4c489.png width=300 height=500 />

Expected : Some demarcation to make it clear if end of the stream is reached

**Comment by kunall17** [comment]
Hmm, correct but the loading messages goes away also right? 
So displaying a toast message should be a right option?

**Comment by yadav-rahul** [comment]
@kunall17 Yes. I agree with you but shouldn't we show loading messages only when new messages are there?

**Comment by kunall17** [comment]
While loading new messages here https://github.com/zulip/zulip-android/blob/a4374c12240d3714710f2dac4376dbecc692a49c/app/src/main/java/com/zulip/android/activities/MessageListFragment.java#L134 
We initiate the process of **trying** to load new messages so then loading messages appear!

**Comment by kunall17** [comment]
#344 is being worked on!
