### ISSUE TITLE
Implement switching between Day/Night mode without restarting activity for better UX 

### ISSUE THREAD

**Issue by sashafierce** [zulip/zulip-android#307]

**Comment by kunall17** [comment]
How will you achieve this? 
This is how the AppCompat library works?

Changing every colors manually isn't the best option!

**Comment by sashafierce** [comment]
Right , that won't be a better trade-off definitely.

**Comment by kunall17** [comment]
So this can be closed?

**Comment by sashafierce** [comment]
Yes closing it
