### ISSUE TITLE
Small issues in UI 

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#309]
1. On narrowing to our self title is not set. 
![videotogif_2017 01 18_09 11 04](https://cloud.githubusercontent.com/assets/18511177/22051649/bdd613c8-dd6a-11e6-9400-52a066e9fb00.gif)

2. On narrowing to PM it will be better to automatically set Person field.
And on narrowing to stream set stream field in message dialog, on narrowing to specific topic of stream set stream name and topic. 
![videotogif_2017 01 18_09 14 49](https://cloud.githubusercontent.com/assets/18511177/22051695/f72a0576-dd6a-11e6-980c-156da620e1e6.gif)
 

3. When drawers are open and if user presses back button it should first close drawer. 
![videotogif_2017 01 18_09 18 44](https://cloud.githubusercontent.com/assets/18511177/22051767/9ae9994c-dd6b-11e6-9fd1-f38305b2c47c.gif)

4. In home if user presses back button twice it finishes app but toast is still showing, which doesn't look good. (above GIF)

5. If messages list is less and doesn't occupy full screen then on scroll toolbar toggle, which doesn't look good. It will be better to restrict toolbar to toggle if message list is less (doesn't occupy full screen)  
![videotogif_2017 01 18_09 20 25](https://cloud.githubusercontent.com/assets/18511177/22051882/55079b76-dd6c-11e6-8e24-f880f9664de5.gif)
 
6. On logging to localhost server after login, login activity is not finished.
![videotogif_2017 01 18_09 22 32](https://cloud.githubusercontent.com/assets/18511177/22051979/14228b7e-dd6d-11e6-88fa-737f2c93f1a9.gif)

7. If the entered server url is wrong cursor of the edittext is set to start, it will be better to set it at last so that user can easily correct url.(pressing back button)

8. When new message is arrived snackbar is show whose start animation is from bottom, which should be from top.(as we are showing snackbar at the top) 
![videotogif_2017 01 18_09 07 44](https://cloud.githubusercontent.com/assets/18511177/22051634/a88bb7b6-dd6a-11e6-8d70-04dae38b78cf.gif)

I think this are bugs, let me know if they are intentionally done like that.
All this are small issue and will don't take much time and should be included in our next upcoming release.  
@timabbott @kunall17 @Sam1301 your views on this

**Comment by Sam1301** [comment]
@vishwesh3 nice. From the gifs I am guessing you found these issues on your branch `sort-people-drawer`. Can you please switch to a branch which is up-to-date with zulip-android/master? Thanks!

**Comment by Sam1301** [comment]
Thanks @vishwesh3 for finding these bugs :+1:  
I would agree with the 1), 4), 5), 6) and 8).
About 2), 3) and 7) I am not sure if we can consider them as issues ( cc: @kunall17).

**Comment by shreyasnbhat** [comment]
Hey!
New here. Could i work on this?

**Comment by saketkumar95** [comment]
@vishwesh3 Thanks for reporting. The toast part was done by me so i will fix that and update this soon. :)

**Comment by vishwesh3** [comment]
Hi @shreyasnbhat Welcome to zulip.
Thanks for your interest in this. I am almost done with this, just waiting for review on some points before creating PR.

**Comment by kunall17** [comment]
@vishwesh3 I agree in all of them, 7th can be neglected its not a big issue!
Send a PR fixing these issues, and separate each issue in its own commit! 

Suggestion: Deal with 5th and 8th at the last, AFAIR the code base they aren't that easy to be solved!

**Comment by timabbott** [comment]
Which parts of this are still open?

**Comment by Sam1301** [comment]
3) and 8) are open in #339
