### ISSUE TITLE
Please put SOMEWHERE easy to find that building requires Gradle 1.5

### ISSUE THREAD

**Issue by ryansnowboarder** [zulip/zulip-android#31]
For new developers, please give them the heads up that building the project requires Gradle 1.5. We could add a "+" to the gradle.build file so that Gradle versions 1.5 or newer can be used, but that might lead to unpredictable and non-reproducible errors because different builds could use different versions of Gradle.

**Comment by lfaraone** [comment]
Hm, perhaps I'm missing something. I see we have a requirement:

```
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
    }
```

… but yet I seem to be using Gradle 2.8 just fine:

```
~/src/zulip-android$ ./gradlew
:help

Welcome to Gradle 2.8.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL

Total time: 4.371 secs
```

**Comment by ryansnowboarder** [comment]
I too tried to compile with Gradle 2.8, which was right after I cloned the
repo, and it failed. Then I added Gradle 1.5 so that I have both Gradle 2.8
and Gradle 1.5. Now it compiles just fine. This is weird...
