### ISSUE TITLE
Narrow to a particular date doesn't show the messages posted on that day exclusively.

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#310]
When I narrow to a particular date using enter date, sometimes I see messages from previous day as well.

![screenshot_20170119-021640](https://cloud.githubusercontent.com/assets/14239866/22083967/314f7cfc-ddf4-11e6-9a80-e35e3357ea43.png)

**Comment by yadav-rahul** [comment]
Yes @Sam1301. I agree with you. Actually there are many bugs in the PR made by @vishwesh3.

@kunall17 I think we should revert `Enter Date`  PR till all issues related to it are resolved?

**Comment by vishwesh3** [comment]
Thanks @sam1301 for reporting. I will look into this and update soon.

**Comment by vishwesh3** [comment]
I have solved this issue using #311. Can you please try this solution on your device and let me know if this issue still persists?

**Comment by Sam1301** [comment]
tried the changes :+1:

**Comment by kunall17** [comment]
@yadav-rahul what other issues are you facing?

**Comment by yadav-rahul** [comment]
@kunall17 As @anuradhagupta345 mentioned in #303, `Enter Date` feature was not working in my app too.
Also when I go to particular date and then press `One Day Before` then also it was showing no messages.

**Comment by kunall17** [comment]
@vishwesh3 
>Also when I go to particular date and then press One Day Before then also it was showing no messages.

**Comment by vishwesh3** [comment]
Working on this and update soon.

**Comment by vishwesh3** [comment]
I have solved and updated PR https://github.com/zulip/zulip-android/pull/311. Now date filtration from local DB is successfully working.Let me know if this still persists. 
Once https://github.com/zulip/zulip/issues/3406 is solved we will able to fetch messages of a specific date and will no longer be dependent on only local DB.
