### ISSUE TITLE
Adding templates for issues and Pull Requests 

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#313]
https://github.com/blog/2111-issue-and-pull-request-templates

This will make sure that important information is not missed in issue.
**Points in issue template**
- Actual Behaviour
- Expected Behaviour
- Steps to reproduce it
- LogCat for the issue
- Screenshots of the issue
- Would you like to work on the issue?

**Check box in Pull Request template**

- [ ]  Code is formatted Mac: `Option + Command + L` Windows: `Ctrl + Alt + L` Linux: Go to `File->Settings->(under IDE settings)->Keymap` and change shortcut as `Ctrl + Alt + L` locks linux.
- [ ]  Make sure BUILD is SUCCESSFUL after running `./gradlew lintDebug` in terminal

**Comment by vishwesh3** [comment]
@timabbott @kunall17 @Sam1301 your views on this?

**Comment by kunall17** [comment]
Hmm, interesting 
Also a check if the PR is related to UI then it works, shows well for the black theme that part misses frequently!

**Comment by vishwesh3** [comment]
Working on this and create PR soon :)
