### ISSUE TITLE
Regarding snackbar notification

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#315]
1. When snackbar is shown and on clicking **Show** button user id narrowed, and then again coming to home user can not find that new message at the end of the list. On the other hand if snackbar is auto hidden new message is added to list.
![videotogif_2017 01 21_05 10 45](https://cloud.githubusercontent.com/assets/18511177/22169284/f19c8428-df98-11e6-821f-71d5506cb865.gif)

2. On clicking **Show** button user is narrowed, it will be better to scroll to the latest(new) messages.
![videotogif_2017 01 21_05 15 50](https://cloud.githubusercontent.com/assets/18511177/22169285/f1a32422-df98-11e6-805e-86abcfa4f830.gif)

2. As of now snackbar is show even if we are sending message. I don't think snackbar notification is required for own send messages.
![videotogif_2017 01 21_05 12 48](https://cloud.githubusercontent.com/assets/18511177/22169283/f19ba95e-df98-11e6-9178-ab654bc70281.gif)

Please review and let me know, this are bugs or intentionally done like this. I would love to work on this.

**Comment by kunall17** [comment]
If the 1st one is the bug it should be not specific to the snackbar, as I used doNarrow only

For the second one its based on the pointer and is a user dependent as clicking on show would skip unread messages and display the latest one! 
If this one is too be done there can be added a callback here
https://github.com/zulip/zulip-android/blob/master/app/src/main/java/com/zulip/android/activities/MessageListFragment.java#L479 and in this callback scroll to complete bottom!

3rd One, this is unexpected and I remember while creating the PR i didn't face this one, anyways do you want to fix this one or should I ?

@vishwesh3 Thanks for reporting these bugs! :) 👍

**Comment by Sam1301** [comment]
the first one might be related to #226.

**Comment by vishwesh3** [comment]
I will be happy to fix it. I am starting work on this and in the meanwhile try to find the cause of real cause 1.  
Thanks @kunall17 @Sam1301

**Comment by kunall17** [comment]
Go ahead for the fixing part, and cover the animation also (if possible)

**Comment by kunall17** [comment]
Can be closed now!

**Comment by vishwesh3** [comment]
yeah this can be closed now
