### ISSUE TITLE
EditText's text disappearing on changing the screen orinentation in Login Activity  

### ISSUE THREAD

**Issue by harshitagupta30** [zulip/zulip-android#320]
**Actual Behaviour**

![videotogif_2017 01 23_23 40 58](https://cloud.githubusercontent.com/assets/12701036/22216992/4cb52196-e1c7-11e6-80ed-da4ace55d9b5.gif)

**Expected Behaviour**
The EditText should retain its text on changing the screen orientation.

@Sam1301 @timabbott @kunall17 Hi, I would like to work on this. Can I send the PR for the same?

**Comment by Sam1301** [comment]
@harshitagupta30 go for it :+1:
