### ISSUE TITLE
App Closes on pressing Back with Compose box open

### ISSUE THREAD

**Issue by sampritipanda** [zulip/zulip-android#322]
If the compose box is open, and I press the back button, the app closes.

The expected behavior in this case should be that only the  compose box closes.

**Comment by kunall17** [comment]
It depends on the UX preference, I would not prefer this to happen as I would rather scroll or swipe this **chatBox** to close this!

**Comment by saketkumar95** [comment]
@sampritipanda Thanks for reporting this. Are you working on this or should i fix?
