### ISSUE TITLE
NavigationDrawer not working smoothly on clicking some stream. 

### ISSUE THREAD

**Issue by harshitagupta30** [zulip/zulip-android#323]
**Actual Behaviour**

![videotogif_2017 01 24_19 19 27](https://cloud.githubusercontent.com/assets/12701036/22249857/b969d6da-e26a-11e6-9571-b45c4763aeb8.gif)

**Expected Behaviour**
Along with message list getting refreshed the navigation drawer should also get closed on clicking any stream. 

@Sam1301 @kunall17 @timabbott Can I send the PR for the same?

**Comment by saketkumar95** [comment]
@harshitagupta30 Please refer  https://github.com/zulip/zulip-android/pull/195 and https://github.com/zulip/zulip-android/issues/288 :)

**Comment by kunall17** [comment]
Can be closed, when the expandableListView will be working this confusion will go away, sam1301 is working on it currently!

**Comment by harshitagupta30** [comment]
Alright! Thanks! @saketkumar95 @kunall17
