### ISSUE TITLE
Making stream un-editable in chatbox when redirected from a particular stream.

### ISSUE THREAD

**Issue by harshitagupta30** [zulip/zulip-android#324]
**Actual Behavior**
![screenshot_2017-01-24-18-40-05](https://cloud.githubusercontent.com/assets/12701036/22251779/03bccc36-e272-11e6-8df6-61315bcbfe58.png)

**Expected Behavior**
![screenshot_2017-01-24-18-39-47](https://cloud.githubusercontent.com/assets/12701036/22251756/f42e6af4-e271-11e6-86df-f156c4d468f6.png)
The user should not able to change the stream when he is redirected from the clicking drawer item.

@kunall17 @saketkumar95 @Sam1301 Please Review! Can I send the PR for the same?

**Comment by kunall17** [comment]
We mostly follow the UX from the web UI this is like blocking the user from sending messages (Its not necessary if I am narrowed to android then i would not send messages in ios stream) , 
I would not recommend this type of blockage, it would be better notify the user if they are **narrowed** to a stream and they enter another stream then they would be notified that this is of other stream like in the web UI!

**Comment by harshitagupta30** [comment]
I totally understand your point but I made it because if a user is entering into a particular session then he should able to send it to only stream, in case if he want to switch he can change the stream from the drawer. 
Thanks for clarifying! @kunall17  :)

**Comment by kunall17** [comment]
This can be closed!
