### ISSUE TITLE
Keyboard keeps popping up when Theme is changed after typing a message

### ISSUE THREAD

**Issue by nitish1211** [zulip/zulip-android#325]
The keyboard does not hide after there is a change in theme when the user is typing the message. Then this keeps up in a cycle as and when i keep changing the theme.

![g_20170125_0222423](https://cloud.githubusercontent.com/assets/13676490/22266619/b62f99dc-e2a6-11e6-8598-a59547be0ce2.gif)

@kunall17 @timabbott . I'd like to work on this.

**Comment by yadav-rahul** [comment]
Yes. If keyboard is open and we change the theme then keyboard remains there and we have to press back button to cancel it.
Instead keyboard should auto-hide itself as soon as new theme is selected.
@Sam1301 @kunall17 What do you think about this?

**Comment by Sam1301** [comment]
I think the chatbox can be made visible(and fab hidden) in this case. That would reflect a seamless transition between the two themes. @kunall17 what are your thoughts on this issue?

**Comment by kunall17** [comment]
@Sam1301 yeah we can go with that ..! :)

**Comment by nitish1211** [comment]
I'll send a PR for this soon

**Comment by anuradhagupta345** [comment]
@nitish1211 Have you started working on this? If not, I would love to fix it!
