### ISSUE TITLE
When starting a new message in a stream/topic narrow via the pencil, auto-fill stream/topic and open keyboard for content

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#330]
This should make this common workflow for starting a reply involve a lot fewer touches.

**Comment by vishwesh3** [comment]
Auto fill part done in PR https://github.com/zulip/zulip-android/pull/317 addressing https://github.com/zulip/zulip-android/issues/309 (2 one). Will update and include Keyboard part in that. :)

**Comment by timabbott** [comment]
@vishwesh3 was 8449ec513516985b66b7993a20dc540d7fe8e921 meant to close this, or only part of it?

**Comment by vishwesh3** [comment]
Yes this issue is solved now.
