### ISSUE TITLE
Add a nicer indication when at the bottom/top of the feed

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#331]
On web and iOS, we've been experimenting with showing a black Zulip logo at the top/bottom of the feed (you can see it on chat.zulip.org easily; we also use this as the place to show loading indicators if new messages are being fetched on either end.  We should probably do the same on Android to replace the whitespace at the bottom (and put it at the top as well).

**Comment by nitish1211** [comment]
@timabbott  I'd like to work on this. So basically we'll be using a custom progressbar at the bottom and on top when loading messages.

**Comment by timabbott** [comment]
I think that's right.

**Comment by kunall17** [comment]
Fixed via #341
