### ISSUE TITLE
Allow narrowing to stream / thread 

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#34]
On the web interface, clicking on the stream or thread will narrow the view to just those messages.  The Android app should do the same.

**Comment by bgilbert** [comment]
It does: just long-press on the message and select the appropriate narrow command.

**Comment by niftynei** [comment]
Oh cool. That's a hard to discover feature. It's good to know it exists.

It's worth pointing out that that doesn't address the issue highlighted in this ticket -- that the Android app behavior is different than the web client, which is what this issue proposes fixing.

**Comment by niftynei** [comment]
Hm. I realized that this intent wasn't explicit in the message title, owing to the fact that I was under the mistaken assumption the functionality didn't exist. Thanks for pointing it out!
