### ISSUE TITLE
HTTPS in capital showing error

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#345]
1) When HTTPS in capital is entered it is showing error. 
![videotogif_2017 01 26_20 44 19](https://cloud.githubusercontent.com/assets/18511177/22405702/9a7e3eae-e66c-11e6-93d4-d731db48a237.gif)

Whereas in browser
![videotogif_2017 01 26_20 41 58](https://cloud.githubusercontent.com/assets/18511177/22405703/9aee4762-e66c-11e6-9937-528aaa0f06b7.gif)

2) If it is then changed to "https" then url editText error is not set to null.

Should I go for it?

**Comment by timabbott** [comment]
I wouldn't have thought anyone would have typed `HTTPS`, but seems reasonable to force-lower-case the server URL when they enter it; it's a quick change and not likely to cause problems.
