### ISSUE TITLE
Scroll position not maintained when messages are loaded ABOVE

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#353]
I noticed the scroll position in recyclerview is not maintained whenever messages are loaded with `LoadPosition.ABOVE` i.e. above the list of visible messages.

Scenarios when this occurs

- scroll to top in any view (home or narrowed)
- narrow to a stream/topic/pm

![g_20170131_1930253](https://cloud.githubusercontent.com/assets/14239866/22468158/5d173002-e7ed-11e6-8dce-195eb6eed3cd.gif)

**Comment by harshitagupta30** [comment]
Hi @Sam1301! Will you be working on this issue? In case you're not then I would love to do that :)

**Comment by Sam1301** [comment]
Hi @harshitagupta30, already did #279 :)

**Comment by harshitagupta30** [comment]
@Sam1301 No problem! :+1:  :)
