### ISSUE TITLE
While scrolling display a scroll to latest message button! 

### ISSUE THREAD

**Issue by kunall17** [zulip/zulip-android#355]
While scrolling display a scroll to latest message button left bottom side maybe!

**Comment by vishwesh3** [comment]
I would like to work on this awesome feature :)

**Comment by kunall17** [comment]
@vishwesh3 go ahead! :)

**Comment by kunall17** [comment]
@vishwesh3 Already there is #326 which is same please stop the work as its already being worked on!

**Comment by vishwesh3** [comment]
Ok, I will be happy to help there :)
