### ISSUE TITLE
Upgrade gradle version to 2.2.3 for faster build with instant run

### ISSUE THREAD

**Issue by nitish1211** [zulip/zulip-android#357]
I think changing the gradle version to 2.2.3 to the current 2.2.0 makes instant run much faster. So it would be easier to test the code.

**Comment by yadav-rahul** [comment]
Yes. It will be useful because we have to manually increase it while testing app in order to enable _Instant Run_.

**Comment by kunall17** [comment]
Yeah ok, send a PR 
Btw for these small changes you can directly send a PR if its not needed then it will be closed!

**Comment by kunall17** [comment]
This can be closed now!
