### ISSUE TITLE
No check on internet connectivity while loading the messages on cold start.

### ISSUE THREAD

**Issue by harshitagupta30** [zulip/zulip-android#366]
On opening the application if there is no internet connectivity and someone is already logged in then the message loading will continue for indefinite period. Neither the messages will be loaded nor the toast will be displayed regarding no internet connection.

![videotogif_2017 02 04_22 44 03](https://cloud.githubusercontent.com/assets/12701036/22620247/750b26e4-eb2d-11e6-9418-de430116bc98.gif)

@kunall17 @timabbott @Sam1301 Please review!

**Comment by vishwesh3** [comment]
Thanks @harshitagupta30 for reporting. After this merge https://github.com/zulip/zulip-android/pull/316#issuecomment-275897250 messages will be shown in offline mode.

**Comment by harshitagupta30** [comment]
@vishwesh3 Thanks for letting know! I am closing this issue! :+1:
