### ISSUE TITLE
Add progress dialog

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#369]
While connecting to the server after selecting `http` or `https` from dialog, app is connecting to server in background, it will be better to add progress dialog to let user know that background process is going on and no need to press  **Enter** button again. It will even help when internet connectivity is slow. Same for the **Refresh** and **Logout**. As it takes some time to drop current database.

Should I go for it?

**Comment by kunall17** [comment]
Yeah, so when your making the ProgressDialog make this in util class and the reuse the dialog, maybe in the later point of time we'll implement some custom loading animations like in the web!
