### ISSUE TITLE
Hide extra "/api" in server url after logout.

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#375]
After logout, the previously entered server url shows extra "/api".

![g_20170210_0036143](https://cloud.githubusercontent.com/assets/14239866/22799008/30312914-ef2a-11e6-9ac6-b0e76b7b0c1e.gif)

Since the old api.zulip.com doesn't exist anymore, we should hide "/api" from the user and use it in the code instead.

**Comment by timabbott** [comment]
Agreed!

**Comment by nitish1211** [comment]
@Sam1301 @timabbott I'll be working on this.

**Comment by saketkumar95** [comment]
@nitish1211 go ahead. :)

**Comment by Sam1301** [comment]
Fixed via #400
