### ISSUE TITLE
Background color of compose status in night theme is white.

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#376]
The background and text color of compose status in chatbox is white under night theme.

![screenshot_20170210-005751](https://cloud.githubusercontent.com/assets/14239866/22799723/d33bc9e6-ef2c-11e6-94bb-3c8981e202f9.png)

**Comment by nitish1211** [comment]
@Sam1301 I'll be working on this.

**Comment by Sam1301** [comment]
@nitish1211 thanks for resolving this issue. Did you know that you can include "Fixes #issue-no" in the commit message and the issue will be auto-closed when the commit is merged? You can checkout https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages for more details on this :)
