### ISSUE TITLE
Add support for login via web

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#383]
We have a few login mechanisms that we're unlikely to want to build into the app natively (both corporate SSO type things like Apache REMOTE_USER and things like GitHub auth).  

To support these more unusual login flows, I think maybe we should support "login via web", where basically the app logs into the Zulip website using a web authentication flow, but then rather than loading the website, it instead could just grab a credential and pass it back to the app.

It will likely require some server changes to support this (mainly either just supporting the redirect-at-the-end piece to get an API key), so probably best for whoever works on this to have a working Zulip development server and familiarity with our backend.

**Comment by meghalagrawal** [comment]
Do we need to do this?

As we are moving towards React Native app so What do you suggest ??

**Comment by timabbott** [comment]
Yeah I think this is a sufficiently marginal feature that we should just skip it.  We just implemented this feature in the RN app.
