### ISSUE TITLE
Add a floating recipient bar

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#385]
Right now, it can sometimes be pretty hard to tell what stream/topic you're looking at in the home view (or which topic in a stream view) that has a lot of messages in a row to the same topic, because we don't have a floating recipient bar showing the stream/topic (or whatever the recipient is) for the messages at the top of the view.  The webapp does this well, as does the React Native iOS app.

**Comment by vishwesh3** [comment]
I would like to work on this.

**Comment by Sam1301** [comment]
@vishwesh3 go for it :+1: :)

**Comment by vishwesh3** [comment]
Right now if same user send multiple messages continuously then his/her name field is added again along with message. I think it will be better to do something like web

![148865237163881](https://cloud.githubusercontent.com/assets/18511177/23581290/27df9fba-0137-11e7-86a1-13572fc61e25.png)
 

![screenshot_1488651457](https://cloud.githubusercontent.com/assets/18511177/23581218/131043d8-0136-11e7-9452-68b24c2f7a72.png)


@timabbott @kunall17 @Sam1301 Your thoughts?

**Comment by timabbott** [comment]
Yes, definitely.

**Comment by vibhav16** [comment]
i would like to work on this issue.

**Comment by vishwesh3** [comment]
@vibhav16 Thanks for your interest in this.
This is already fixed in https://github.com/zulip/zulip-android/pull/437
