### ISSUE TITLE
Narrow to @ messages 

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#39]
Is there a way to narrow to @-messages in the app?  Perusing the app, I haven't been able to find one.

**Comment by timabbott** [comment]
I don't think so.  Would be a great feature certainly, and fairly implementable since whether or not the user has been mentioned is tagged in the `flags` field on the message objects sent from the server.

**Comment by kunall17** [comment]
@vishwesh3 you already done this in #297 so I assigned you!
