### ISSUE TITLE
Testing zulipbot

### ISSUE THREAD

**Issue by vishwesh3** [zulip/zulip-android#401]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**

Explain what is currently happening.

**Expected Behaviour**

Explain what you expected (unnecessary if it's obviouxly broken, e.g. a crash).

**Would you like to work on the issue?**

@zulipbot claim-issue

**Comment by synicalsyntax** [comment]
@vishwesh3 You have to leave a comment on the issue you want to claim, but I think we can add support for zulipbot in the body of an issue too. What do you think @timabbott ?

**Comment by vishwesh3** [comment]
Thanks @synicalsyntax
 Just opened this issue to check whether zulipbot works when "@zulipbot claim-issue" is in the body.
