### ISSUE TITLE
Make sure that all of our strings have the standard Zulip capitalization scheme

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#405]
Generally, just the first letter of phrases is capitalized in Zulip, even in headings/etc.  E.g.
```
Search Messages -> Search messages
Find Users -> Find users
```

**Comment by saketkumar95** [comment]
yeah, i will check all the strings, if found such then do the changes. :)

**Comment by saketkumar95** [comment]
@timabbott what about the string "Welcome to Zulip!" ? should i change that too?

**Comment by Sam1301** [comment]
@saketkumar95 I guess not, proper nouns can be left capitalized.

**Comment by timabbott** [comment]
Yeah, capital nouns should be left capitalized as normal :).
