### ISSUE TITLE
UI Bug While logging in

### ISSUE THREAD

**Issue by nikhilbalyan** [zulip/zulip-android#421]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**

Right now the Sign In and LOG IN text is not center aligned

**Expected Behaviour**

The text of Sign In and LOG IN should be center aligned

**Would you like to work on the issue?**

Yes I would love to work on this issue

**Comment by Sam1301** [comment]
@nikhilbalyan Actually this will be taken care of in #392

**Comment by nikhilbalyan** [comment]
@Sam1301 ok closing then my bad
