### ISSUE TITLE
Make it possible to see previous message when replying

### ISSUE THREAD

**Issue by niftynei** [zulip/zulip-android#43]
Right now when you reply to a message, there's no easy way to see what the previous message was. It'd be nice to change the reply-to message dialog to an interface that allows you to view the previous message more easily.

Here's some examples of how other apps have fixed this:
- Twitter: pull down to view previous tweet
- Slack/Hangouts: response box is inline to the message stream

![screenshot_20160401-101944](https://cloud.githubusercontent.com/assets/1097769/14212061/221041da-f7ff-11e5-9565-0e0257d25faa.png)

![screenshot_20160401-102035](https://cloud.githubusercontent.com/assets/1097769/14212062/2213fcee-f7ff-11e5-95b9-62371ffd0476.png)

**Comment by ryansnowboarder** [comment]
I'm trying to fix some things on the Android app and I'm hitting a wall while logging in. How do I do that (requires a @zulip.com login)?

**Comment by niftynei** [comment]
duplicate of #8
