### ISSUE TITLE
Tutorial on first launch

### ISSUE THREAD

**Issue by DravitLochan** [zulip/zulip-android#436]
**Actual Behaviour**

Similar to the first time tutorial in web client we may implement the same in the android application.

**Expected Behaviour**

User goes through various features of the android application. For those who are reinstalling, we may provide a skip button.

**Would you like to work on the issue?**

Yes

**Comment by DravitLochan** [comment]
@zulipbot claim

**Comment by saketkumar95** [comment]
Already doing in https://github.com/zulip/zulip-android/issues/392

**Comment by DravitLochan** [comment]
doing an Intro-slider ?

**Comment by saketkumar95** [comment]
Yes! :)

**Comment by DravitLochan** [comment]
I am looking at a different picture. Intro slider should be made with respect to what the application is all about. Rest should be implemented using tutorials.  this will give you a better picture :)
![tut](https://cloud.githubusercontent.com/assets/14837478/23580047/0477181c-0120-11e7-8b00-2c72c151f6d3.PNG)

**Comment by nitish1211** [comment]
I think that's a great idea. You can use the [material ShowCaseView](https://github.com/deano2390/MaterialShowcaseView). 
@saketkumar95 @kunall17 Your thoughts on this?

**Comment by saketkumar95** [comment]
@nitish1211 @DravitLochan Yeah! This all is already discussed here https://chat.zulip.org/#narrow/stream/android/topic/tutorial.20designs. I'm working on the designs right now, was busy with other assigned issue. We need to have the intro sliders and have the option of help in overflow menu, which will launch this tutorials again. :) We are not planning for the showcase right now.

**Comment by DravitLochan** [comment]
i see that it has already been discussed. so how do we proceed? are you implementing both of them?

**Comment by saketkumar95** [comment]
yeah already done earlier. But now implementing it here https://github.com/zulip/zulip-android/issues/392

**Comment by DravitLochan** [comment]
ok. please look at #434 and #435 :)

**Comment by saketkumar95** [comment]
You can close this issue now!
