### ISSUE TITLE
Have Questions - Profiling App Startup

### ISSUE THREAD

**Issue by ryansnowboarder** [zulip/zulip-android#44]
I'm attempting to profile the app with Debug.startMethodTracing() and Debug.stopMethodTracing(). I've got some questions about the app:

1) What do I use to login - credentials, run zulip dev server, etc.?
2) Where is a good place to stop method profiling of app startup (I was thinking end of loginActivity)?

I was thinking of separating method and function calls into independent of internet and dependent of internet. For independent calls, I'd look into code optimization; for dependent calls, I'd look into caching methods first, perfect those, and then look into code optimization. Thoughts?

**Comment by ryansnowboarder** [comment]
@timabbott?

**Comment by timabbott** [comment]
The short answer is that you can use this hack:
https://github.com/zulip/zulip-android/blob/dfdf23a7769fa4602735c13dfe95c21f6b913337/app/src/main/java/com/zulip/android/ZulipApp.java#L134
which means that if you try to login as iago@zulip.com, it should connect to a local development environment running on your laptop.

We should both document this mechanism and also provide an improved workflow; in many ways fixing this is similar work to fixing #1 (which I think @niftynei has been taking a look at).

**Comment by ryansnowboarder** [comment]
I've been fussing around with different versions of that hack for a few hours and haven't had any luck. See my latest issue for details. 

Once this gets figured out I'll be happy to document it.
