### ISSUE TITLE
Close stream expansion on clicking on open stream

### ISSUE THREAD

**Issue by nitish1211** [zulip/zulip-android#443]
**Actual Behavior**
The expansion of a stream in Nav Drawer stays open until another stream is opened.

**Expected Behaviour**
Clicking on an open stream name should close the expanded list.

@kunal17 @saketkumar95 I'll be working on this.

**Comment by nitish1211** [comment]
@zulipbot claim-issue

**Comment by abhaymaniyar** [comment]
I have already started working on it.

**Comment by abhaymaniyar** [comment]
@nitish1211

**Comment by abhaymaniyar** [comment]
See #439.

**Comment by abhaymaniyar** [comment]
Make sure to close this issue :)
