### ISSUE TITLE
App goes to Home screen on switching theme in a particular stream.

### ISSUE THREAD

**Issue by abhaymaniyar** [zulip/zulip-android#444]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

When the user enters a particular stream and then switches theme, the app throws the user to the MainActivity of the app.

Explain what is currently happening.

**Expected Behaviour**

The app should remain to the stream where the user switched the theme.

**Would you like to work on the issue?**

Yes

**Comment by abhaymaniyar** [comment]
claim-issue @zulipbot

**Comment by abhaymaniyar** [comment]
@zulipbot claim-issue

**Comment by vishwesh3** [comment]
Fixed in https://github.com/zulip/zulip-android/pull/414#issue-208965114 (Switching theme in narrowedView)
