### ISSUE TITLE
Crashlytics Error

### ISSUE THREAD

**Issue by ryansnowboarder** [zulip/zulip-android#46]
> 04-08 17:28:01.669 9253-9253/com.zulip.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.zulip.android/com.zulip.android.ZulipActivity}: com.crashlytics.android.CrashlyticsMissingDependencyException: 
                                                                 This app relies on Crashlytics. Configure your build environment here: 
                                                                 https://crashlytics.com/register/7c523eb4efdbd264d6d4a7403ee7a683b733a9bd/android/com.zulip.android

> 

I followed the link and it now gets redirected somewhere else - looks like Crashlytics updated and is trying to deprecate what's in our app?

**Comment by niftynei** [comment]
Yeah, Crashlytics is out of date.  That error should be fixed in master now tho.  Can you check that you've pulled the latest from master and that you're building the `debug` version of the app?

**Comment by niftynei** [comment]
Closing; this issue has been resolved in master.
