### ISSUE TITLE
Support using the app with multiple realms without constantly logging in/out

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#47]
It's likely that we'll have an increasing number of users using Zulip in multiple realms (or even servers), and it'd be great for the Android app to support being logged into multiple accounts at the same time.

There's probably a lot of UI details to figure out to make this work...

**Comment by ryansnowboarder** [comment]
If it's one user with multiple accounts, I think it would be a nuisance to switch back and forth between accounts on a front-end UI. Could we blend multiple accounts into the same UI - that is, show multiple account data blended together so it's one front-end experience with multiple back-ends?

**Comment by hi-ko** [comment]
Is there any progress for multiple accounts / servers in the sampe Andoid App?
Push message should be shown for all accounts configured and clicking on a notification should switch to the correct account in the android app.

**Comment by timabbott** [comment]
This is the wrong repository for the current Zulip mobile app; see http://github.com/zulip/zulip-mobile.  That project does, as of recently, switch on clicking a notification.
