### ISSUE TITLE
Build a slick login experience when DevAuthBackend is enabled on web

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#48]
This is probably actually a joint Android/server project, but it'd be great if when you pointed the Android app at a Zulip server that's using DevAuthBackend (which shows the grid of users to login as on the web for development), if we could provide a similar experience on mobile where it just shows a list of users and you can click to login as any of them, so one doesn't need to spend time dealing with passwords when developing against a development server.

**Comment by ryansnowboarder** [comment]
I'll work on this after I finish profiling the app startup, which should be sometime today or tomorrow.

**Comment by niftynei** [comment]
This has been merged! :)
