### ISSUE TITLE
"HomeList" message fragment list dont show messages on back press

### ISSUE THREAD

**Issue by divs4debu** [zulip/zulip-android#481]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**
The Home fragment appears  empty if pressed back after narrowing the stream and then selecting any sub stream and then pressed back.
![issue_home_list](https://cloud.githubusercontent.com/assets/9443348/24660428/2390e056-196d-11e7-9553-0974a6aa7e1b.png)

Here is the short video too.
[https://drive.google.com/open?id=0BzZnaFq4F3EdS0VfcXZsR3h6SG8](url)
**Expected Behaviour**

The expected behaviour is to  show home fragment with the messages.
**Would you like to work on the issue?**
Yes 
Let us know if this issue should be assigned to you.

**Comment by kunall17** [comment]
Fixed via 855755bb549cac7ebac65236ee61df7fd2253e9a
