### ISSUE TITLE
Appbar layout doest not show back on scrolling down.

### ISSUE THREAD

**Issue by divs4debu** [zulip/zulip-android#482]
[Read our guide on bug reports here](./ISSUES_GUIDE.md)

**Actual Behaviour**
The Appbar layout in main.xml hides when scroll up but doesnt shows on scroll down.

**Expected Behaviour**
The expected behaviour would be to show both appbar and fab on scroll down.

**Would you like to work on the issue?**

Let us know if this issue should be assigned to you.
YES

**Comment by divs4debu** [comment]
@zulipbot claim

**Comment by divs4debu** [comment]
@kunall17 @Sam1301 Please review this issue

**Comment by kunall17** [comment]
Fixed via 855755bb549cac7ebac65236ee61df7fd2253e9a
