### ISSUE TITLE
Activity and fragment doesnot retain its state

### ISSUE THREAD

**Issue by divs4debu** [zulip/zulip-android#485]
**Actual Behaviour**
On rotation or when turning night mode on the activity restarts and starts fresh and donot retain where we left. 

**Expected Behaviour**
When activity is rotated or in other circumstances like turning on night mode the resulting state must retain the previous state data bundle.

**Would you like to work on the issue?**
This could be solved using onSavedInstanceState and saving fragments in the ZulipActivity.
Yes i would like to work on it .

**Comment by divs4debu** [comment]
@timabbott @kunall17 @saketkumar95 @Sam1301  Please review this issue.

**Comment by kunall17** [comment]
Its already done here, but the PR is WIP https://github.com/zulip/zulip-android/pull/414
