### ISSUE TITLE
Fetch Google OAUTH public key from the server rather than hardcoding zulip.com's

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#49]
This is required to support Google auth with non-zulip.com servers, and thus is a natural follow-up to #1.

See https://github.com/zulip/zulip/issues/102 for details on the backend change that now supports doing this fetching.

**Comment by ryansnowboarder** [comment]
I could work on this after doing #48...

**Comment by niftynei** [comment]
There's some limitations with the Google Oauth APIs for android that limits our ability to do this, see this [zulip-devel](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/zulip-devel/i4682LzDUKw/qxYMvkgNAwAJ) thread for context.

Barring a solution from Google, the best alternative is to allow users to auth themselves with Google via a WebView.

**Comment by timabbott** [comment]
This is solved now, right?

**Comment by niftynei** [comment]
Yep. 👍
