### ISSUE TITLE
Not able to login to chat.zulip.org

### ISSUE THREAD

**Issue by Sam1301** [zulip/zulip-android#494]
logs
`05-04 17:27:08.480 3502-3687/com.zulip.android.dev D/OkHttp: <-- 405 Method Not Allowed https://chat.zulip.org/api/v1/get_auth_backends (1280ms)`

**Comment by timabbott** [comment]
This is probably a result of a server-side change I made to require that request be done as a GET.  I take it we're actually doing a POST?  Can you confirm?

I think the fix for compatibility will be to undo that change in the server, but we may also want to switch the app to use POST.

**Comment by Sam1301** [comment]
>This is probably a result of a server-side change I made to require that request be done as a GET. I take it we're actually doing a POST? Can you confirm?
yep, the app does a POST request

**Comment by timabbott** [comment]
OK, it's a bug in the app but we need to revert the server change.  Thanks for catching this!

**Comment by timabbott** [comment]
Merged 33ecfd7da40a41a2f7c8192c329c4f50f4460a54; I'll deploy it on chat.zulip.org shortly.
