### ISSUE TITLE
login to local dev server through Android device on WiFi or emulator

### ISSUE THREAD

**Issue by ryansnowboarder** [zulip/zulip-android#50]
I've tried the following on WiFi with the login (iago@zulip.com):

- fresh pull of zulip dev environment (12:00AM, EST, 4/13/2016)
- Allow inbound to port 9991 in TCP & UDP in firewall and allow connection from Android device (192.168.1.2)

1. Grab the ip address/port of the host PC (192.168.1.6:9991) and connect to that in the app  on device (failed)
2. Grab the ip address of the guest machine/port on the host PC (192.168.56.1:1234) and connect to that in the app on device (failed)
3. Connect to localhost (localhost, 127.0.0.1:9991) in the app on device (failed)
4. Connect to 10.0.2.2:9991 in the app on emulator (failed)

1,2,4 fail with a timeout. 3 fails with a connection refused, which it should because the phone is connecting to itself.

**Comment by niftynei** [comment]
The `iago` hack is intended to work for reaching a local instance of Zulip via the Android _emulator_, number 4 in your list of things that you've tried.  This is unsupported so I'm afraid I can't offer you much advice or help with this; if you're able to get it working, feel free to submit a pull request with the changes you needed to make.  

Work is currently being done to allow users to log in to a different server, which should obviate this hack; it's slated to be removed once that work is done.  For more info please see #1 .
