### ISSUE TITLE
Reset/resend password option not present

### ISSUE THREAD

**Issue by jsmanrique** [zulip/zulip-android#509]
**Actual Behaviour**

As usual, I have forgotten the password. I don't see an option to reset/send it to my email

**Expected Behaviour**

There is no `forgot password?` checkbox or whatever to ask for resetting or sending it to my email

**Would you like to work on the issue?**

I don't have enough knowledge to do it

**Comment by kunall17** [comment]
Thanks for reporting this! :) 

We are kinda deprecating this native java app, and focusing on the react native cross platform implementation of the app, its in beta phase right now but will be released in the coming weeks and hopefully we'll include this feature.

Would love to hear feedback from you.

**Comment by timabbott** [comment]
@kunall17 do we need a "reset password" option in the new app?  If so, we should transfer this issue to that project and fix it.

**Comment by saketkumar95** [comment]
@timabbott Actually I added the forgot password option in the RN app which currently opens up the reset password link. Checkout this : https://github.com/zulip/zulip-mobile/pull/785

**Comment by timabbott** [comment]
Great!

**Comment by saketkumar95** [comment]
I think we need to close this issue ?
