### ISSUE TITLE
Custom emoji in the emoji picker and auto complete?

### ISSUE THREAD

**Issue by 0rmi** [zulip/zulip-android#519]
Unless it's some bug in my app, custom emotes don't show up in the auto complete list when you start typing :emotename and also can't be found in the emoji picker. Any plans to implement this? Alternatively, could someone point me in the direction of the piece of code where the app grabs the list of emotes to display for auto complete, and the emote picker, so maybe i can try to implement it in my spare time?

**Comment by timabbott** [comment]
I assume you moved this issue to zulip/zulip-mobile, the project that is still in use?

**Comment by 0rmi** [comment]
Yes, i realized i was posting in a depreciated repository
