### ISSUE TITLE
Expand documentation on getting started developing on Zulip Android

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#58]
It'd be great if the Zulip Android app had a "getting started" tutorial and had links to general "getting started" guides for Android.

**Comment by timabbott** [comment]
We should be sure to add notes on how to use DevAuthBackend here.  See https://github.com/zulip/zulip/pull/851#issuecomment-227765373 and following discussion for some notes on how to do this.

**Comment by kunall17** [comment]
@timabbott Yeah sure, I'll write documentation!

**Comment by kunall17** [comment]
@timabbott I was writing documentation for this today, i have written javadocs for many functions in the app + I have to write getting started as well, so should I create a folder docs/ in this repository root like https://github.com/zulip/zulip/tree/master/docs and then those will be rendered at http://zulip.readthedocs.io/en/latest/ ?

**Comment by timabbott** [comment]
That won't happen by default, but it would be easy to set up zulip-android.readthedocs.io to work that way.  You could also just put some markdown files in the root of the repo and link to them from the README.md; Github can render markdown just fine and that might be easier while we don't have a lot of content...

**Comment by timabbott** [comment]
Do we think this is resolved by the new README.md?

**Comment by niftynei** [comment]
I think so. I'll close this for now, we can re-open if need be.
