### ISSUE TITLE
Allow sending messages directly from message view

### ISSUE THREAD

**Issue by bgilbert** [zulip/zulip-android#8]
Allow sending messages from a text box at the bottom of the message view, as in the web app, and eliminate the modal Compose dialog.  This would improve consistency with other Android applications (e.g. Hangouts) and eliminate several problems with the Compose window:

- It covers the discussion being replied to.
- It's not very tall, so long replies are hard to write.
- Accidentally pressing the Android Back button discards the message.

**Comment by niftynei** [comment]
This enhancement will go out in the next full build.

**Comment by timabbott** [comment]
Yay!
