### ISSUE TITLE
Google auth doesn't allow switching accounts

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#86]
On current master, if you login with one Google account, and then log out, and then click the "sign in with Google" button, it doesn't present a picker for which Google account to use -- it just logs you in with the same Google account you used originally.

**Comment by kunall17** [comment]
New AppAuth for google sign in has it's PR here https://github.com/zulip/zulip-android/pull/70 will check for this bug once new API's get's merged in.

**Comment by timabbott** [comment]
@kunall17 I think this bug is still open.

**Comment by kunall17** [comment]
So you mean once we log in using one ID, it doesn't show the account picker anymore right?

**Comment by timabbott** [comment]
right
