### ISSUE TITLE
Remove "Use zulip.com" checkbox and optimize flow for entering server domain

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#88]
zulip.com is ceasing to exist at the end of the month (the users will be migrated to a new server, but the new server setup will probably use a different URL per team (https://github.com/zulip/zulip/pull/1154), so I think we probably just want to get rid of the "use zulip.com" checkbox. It might make sense to just move the login flow to have a 2-step process; with first screen that lets you either select an account you've used before or enter a new server domain, and then the password+Google login options on a second screen.

This will also allow us to present (or not present) the Google login option on the second screen, depending on whether the server has Google auth enabled (using the new https://github.com/zulip/zulip/pull/1077 to determine which backends are supported).

**Comment by kunall17** [comment]
Fixed by #101 and #99 , can be closed now!
