### ISSUE TITLE
Make it clear that there are no messages when narrowing to a view with no messages

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#89]
It'd be great to have a nice clear message indicating that there's never been any messages in a stream/PM thread when you narrow to it via the app rather than just showing a completely empty feed; currently one can be left worrying that maybe there is traffic but the app failed to download it.

**Comment by niftynei** [comment]
This is a great suggestion. @kunall17 I wonder if adding a FAB (FloatingActionBar) would be a good  way to hide it?

**Comment by kunall17** [comment]
Fixed by #102, issue can be closed now!

**Comment by timabbott** [comment]
Agreed, thanks @kunall17!
