### ISSUE TITLE
Muted topics are not hidden

### ISSUE THREAD

**Issue by bgilbert** [zulip/zulip-android#9]
Incoming messages on muted topics are not hidden, either in the home view or in views of individual streams.

**Comment by timabbott** [comment]
Yep muted topics are not supported in the Android app.

**Comment by ryansnowboarder** [comment]
I'm trying to fix some things on the Android app and I'm hitting a wall while logging in. How do I do that (requires a @zulip.com login)?

**Comment by niftynei** [comment]
Fixed as of #42.
