### ISSUE TITLE
Add a way to hide the compose box

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#92]
While having the compose box show up inline is useful, it'd be nice to have a way to hide it for when you just want to have more screen real estate for reading messages (especially relevant when using the app in landscape orientation).

**Comment by kunall17** [comment]
This would really nice to have, I created two ways for this issue one is hiding chatBox and toolbar on scroll and the other one is implementing a FloatingActionButton to show the keyboard on clicking it displays the chatBox and hides it after some seconds (5 secs in the gif), in both these when coming down hide the views and when moving up the list it shows the views.

[Preview of FloatingActionButton](https://cloud.githubusercontent.com/assets/12700799/16932258/f1cc3876-4d62-11e6-98c2-a84f650f9641.gif)
[Preview of ChatBox](https://cloud.githubusercontent.com/assets/12700799/16932257/f1c8c09c-4d62-11e6-9602-3d26ccfc36f1.gif)

I would go for the FAB method, as hiding the chatBox will have issues at the bottom and top it will overlap the list as shown in the GIF + FAB looks good, just need some suggestions for the background color of the FAB!

**Comment by niftynei** [comment]
@kunall17 the FAB looks great!  Once you have the chat box open, how would you collapse back into the FAB again?

**Comment by kunall17** [comment]
When chatbox is displayed after some time [5 seconds in the gif] it would hide the chat box and bring up the FAB, I will add some checks if the user is using the chatbox edittexts it would not hide.
And on scroll if the chatbox is displayed it would hide the chatbox.

**Comment by kunall17** [comment]
@niftynei @timabbott need your final suggestions on this one! I have to implement this in #81 
I'm with FAB method, looks more clean and no bugs which will occur in hiding chatBox as it will overlap the list!

**Comment by timabbott** [comment]
That approach sounds reasonable to me!

**Comment by timabbott** [comment]
(Though I'd consider implementing it as a new PR rather than part of #81, since #81 is already a very large PR, and it can often slow down actually merging changes to keep adding additional new features to an existing PR)

**Comment by kunall17** [comment]
Well AFAIK for coordinator layout scroll flags listView is not supported, a recyclerView is needed for the scroll flags so I will have to add the commits in #81!

**Comment by niftynei** [comment]
As of #81 can now swipe to dismiss the box.
