### ISSUE TITLE
long-pressing on a message's sender bar doesn't do anything

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#93]
It appears that you need to long-press on the message body, not the recipient bar, in order to pop up the long-press menu.  Is there a reason we shouldn't have long-pressing on the recipient bar pop up the long-press menu?

**Comment by kunall17** [comment]
Will be fixed in #81.

**Comment by niftynei** [comment]
@timabbott is this still an issue?  I'm not sure I'm clear on what the "recipient bar" is.

**Comment by timabbott** [comment]
The recipient bar is the thing that says who received the message (i.e. the stream+topic or other people in a PM conversation you're having)

**Comment by niftynei** [comment]
I don't think this was fixed per-se but since the recipient bar is much smaller, is this still an issue?

**Comment by timabbott** [comment]
Haven't tested in the new version.  I do think it's nice if something good happens anywhere you press on the UI, since it can be kinda confusing trying to figure out how to reply if it feels like it only sometimes works..

**Comment by timabbott** [comment]
Just tested this in the new version, and I think actually I'd mis-described the problem.

The problem is that the typical 1-line message to a new recipient has 3 lines: a first line recipient bar, a second line with the sender/timestamp/etc. and a third line with the message content.  Currently, clicking the first line narrows, which is great.  The third line replies to the message.  The second line does nothing.  I think we should change the second line to reply, since from a user perspective it really feels like "replying by clicking only works half the time".

**Comment by niftynei** [comment]
in progress
