### ISSUE TITLE
long-pressing and then selecting a narrowing option opens keyboard tray

### ISSUE THREAD

**Issue by timabbott** [zulip/zulip-android#94]
When you long-press on a message and then select "Narrow to topic" or "Narrow to stream", it opens up the keyboard tray, filling much of the screen.  Since the user selected a narrow option (rather than one of the "reply" options), probably they just want to narrow and see the messages, not start composing a reply.

**Comment by kunall17** [comment]
Will be fixed in #81, there are some bugs in this PR as well, once they are sorted out we'll get this merged!

**Comment by niftynei** [comment]
confirmed fixed.
