### ISSUE TITLE
Screenshot for app install is broken

### ISSUE THREAD

**Issue by rishig** [zulip/zulip-android#95]
This is what I got; not sure what the underlying problem is. 
![screenshot_20160713-163250](https://cloud.githubusercontent.com/assets/890911/16823469/66ff8808-4919-11e6-9155-de0d4e68be12.png)

**Comment by niftynei** [comment]
@rishig can you describe the steps you took to arrive in this state?

**Comment by timabbott** [comment]
I get the same thing -- the process was just installing via the beta link

**Comment by niftynei** [comment]
This will need to be fixed via the Google Dev Console.  See the "Feature Graphic" section [here.](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en)

**Comment by timabbott** [comment]
@niftynei OK do you want to pick out a set of screenshots that we want to upload there as a replacement?  I think once we have that, it should be easy for Luke to update.

**Comment by timabbott** [comment]
I guess we've updated the main screenshots, but still need to make a new "Feature graphic" screenshot...

**Comment by niftynei** [comment]
@kunall17 do you have any interest in making up a new Feature Graphic for the Zulip app?  Our current one is pretty bad.

**Comment by apoorvinfo** [comment]
I can Make New Feature Graphic for the Zulip app.

**Comment by timabbott** [comment]
Yeah that'd be awesome.

**Comment by Sam1301** [comment]
this issue has been resolved (https://chat.zulip.org/#narrow/near/162327/stream/android/topic/play.20store.20screenshots)
